export const quranReadHome = {
  backHome: "العودة للرئيسية",
  quranReadingHub: "مركز قراءة القرآن",
  resetProgress: "إعادة ضبط التقدم",
  readingStats: "إحصائيات القراءة الخاصة بك",
  days: "أيام",
  completedSurahs: "السور المكتملة",
  surahsFinished: "نسبة السور المكتملة %",
  totalVersesRead: "إجمالي الآيات المقروءة",
  totalVersesPercent: "نسبة الآيات المقروءة %",
  overallProgress: "التقدم الإجمالي في القرآن الكريم",
  recentlyRead: "قرأت مؤخراً",
  fullyCompleted: "مكتملة بالكامل",
  readingUpToAyah: "القراءة وصلت إلى آية",
  readyToRead: "جاهز للقراءة",
  resetConfirm: "هل أنت أكيد من رغبتك في إعادة ضبط كل تقدم القراءة الخاص بك؟",
  searchPlaceholder: "ابحث عن السورة بالاسم، الرقم أو المعنى...",
  allSurahs: "جميع السور",
  completed: "مكتملة",
  inProgress: "قيد القراءة",
  notStarted: "لم تبدأ",
  verses: "آيات",
  rukus: "ركوعات",
  juz: "أجزاء",
  surahIndexTracking: "فهرس السور والمتابعة",
  clearInput: "مسح المدخلات",
  recentSearches: "عمليات البحث الأخيرة:",
  removeSearch: "إزالة البحث",
  clearAllHistory: "مسح كافة السجل",
  clearAll: "مسح الكل",
  markAsIncomplete: "تحديد كغير مكتملة",
  markAsCompleted: "تحديد كمكتملة",
  meccan: "مكية",
  medinan: "مدنية",
  noMatchingSurahs: "لم يتم العثور على سور مطابقة.",
  startReading: "ابدأ القراءة",
  surah: "سورة",
  ayah: "آية",
  juzNumber: "رقم الجزء",
  paraJuz: "الجزء",
  sajdahProstration: "سجدة تلاوة",
  yesSajdah: "نعم",
  noSajdah: "لا توجد سجدة في هذه السورة",
  totalWordsEst: "إجمالي الكلمات (تقريبي)",
  totalLettersEst: "إجمالي الحروف (تقريبي)",
  introduction: "مقدمة",
  keyThemes: "المواضيع الرئيسية",
  mainLessons: "الدروس المستفادة",
  virtuesBenefits: "الفيوضات والفضائل",
  periodRevelation: "زمن النزول والسياق التاريخي",
  coreSubjects: "المحاور الأساسية والقضايا العقائدية",
  practicalLessons: "الدروس العملية والحكم للحياة اليومية",
  virtuesSpiritual: "فضائل التلاوة والبركات الروحية",
  reflectionTip: "نصيحة: التدبر العميق في آيات القرآن الكريم هو مصدر الهداية الروحية. هل أنت جاهز؟ عد إلى التلاوة.",
  loadingVerses: "جاري تحميل الآيات القرآنيّة...",
  pleaseWait: "يرجى الانتظار لحظة",
  failedToLoadSurah: "فشل في تحميل بيانات السورة",
  tryAgain: "إعادة المحاولة",
  loadingNextPage: "جاري تحميل الصفحة التالية...",
  backToTop: "العودة إلى الأعلى",
  showSurahSidebar: "إظهار الشريط الجانبي للسور",
  searchVersesInSurah: "البحث عن الآيات في السورة",
  audioError: "فشل في تحميل الصوت للتلاوة.",
  serverError: "خطأ في الاتصال بالخادم.",

  // Options & Tooltips
  quickOptionsMenu: "قائمة الخيارات السريعة",
  closeMenu: "إغلاق القائمة",
  closeRecitation: "إغلاق التلاوة",
  playSurah: "تشغيل السورة",
  searchInSurah: "البحث في السورة",
  changeArabicFont: "تغيير الخط العربي",
  toggleBoldFor: "تبديل الخط العريض",
  changeTextSize: "تغيير حجم النص",
  textSize: "حجم النص",
  changeLineHeight: "تغيير ارتفاع السطر",
  lineHeight: "ارتفاع السطر",
  changeTextAlignment: "تغيير محاذاة النص",
  leftAlign: "محاذاة لليسار",
  centerAlign: "محاذاة للوسط",
  rightAlign: "محاذاة لليمين",
  justifyAlign: "ضبط المحاذاة",
  tooltipSettings: "إعدادات التلميحات",
  tooltipOptions: "خيارات التلميحات",
  translation: "الترجمة",
  transliteration: "النطق اللاتيني (النقحرة)",
  fontSize: "حجم الخط",

  // Sidebar & Navigation
  surahList: "قائمة السور",
  surahs: "السور",
  bookmarks: "العلامات المرجعية",
  notes: "الملاحظات",
  options: "الخيارات",
  shortcuts: "اختصارات",
  keyboardShortcuts: "اختصارات لوحة المفاتيح",
  searchShortcutsPlaceholder: "البحث في الاختصارات...",
  shortcutHelpTitle: "اختصارات مفيدة للوحة المفاتيح",
  shortcutHelpDesc: "مفاتيح سريعة للتنقل والتحكم في قارئ القرآن الكريم.",
  categoryAudio: "الصوت والتلاوة",
  categoryNavigation: "التنقل والقراءة",
  categoryInterface: "الواجهة والبحث",
  shortcutPlayPause: "تشغيل / إيقاف الصوت مؤقتاً",
  shortcutNextVerse: "الآية التالية",
  shortcutPrevVerse: "الآية السابقة",
  shortcutSearch: "فتح شريط البحث",
  shortcutToggleSidebar: "تبديل الشريط الجانبي",
  shortcutBookmark: "حفظ الآية بعلامة مرجعية",
  shortcutNextSurah: "السورة التالية",
  shortcutPrevSurah: "السورة السابقة",
  shortcutCloseModal: "إغلاق النوافذ المنبثقة",
  shortcutScrollTop: "الانتقال للأعلى",
  keySpace: "Space",
  keyArrowRight: "→ السهم الأيمن",
  keyArrowLeft: "← السهم الأيسر",
  keyArrowUp: "↑ السهم للأعلى",
  keyArrowDown: "↓ السهم الأسفل",
  keyEsc: "Esc",
  keyCtrlK: "Ctrl + K",
  keyCtrlB: "Ctrl + B",
  keyShiftN: "Shift + N",
  keyShiftP: "Shift + P",
  noShortcutsFound: "لم يتم العثور على اختصارات مطابقة.",
  recitationAndSearch: "التلاوة والبحث",
  textAppearance: "مظهر النص",
  searchSurah: "البحث عن سورة...",
  recent: "حديثاً:",
  clear: "مسح",
  noSurahsFound: "لم يتم العثور على سور",
  typeMeccanLabel: "مكية",
  typeMedinanLabel: "مدنية",
  versesLabel: "آيات",
  noBookmarks: "لم يتم حفظ أي علامات مرجعية بعد.",
  ayahNo: "آية ",
  hideSidebar: "إخفاء الشريط الجانبي",
  showSidebar: "إظهار الشريط الجانبي",
  closeSidebar: "إغلاق الشريط الجانبي",
  loadAllPages: "تحميل كافة الصفحات",

  // Search & Playback Controls
  searchVersesPlaceholder: "ابحث عن أي كلمة في هذه السورة...",
  resultsFound: "تم العثور على {count} نتيجة",
  noResultsFound: "لم يتم العثور على نتائج. تحقق من الإملاء أو جرب كلمات أخرى!",
  autoplayNextSurah: "تشغيل السورة التالية تلقائياً",
  repeatMode: "وضع التكرار",
  repeatNone: "إيقاف",
  repeatAyah: "الآية",
  repeatSurah: "السورة",
  repeatAll: "الكل",
  detailsAndInfo: "التفاصيل والمعلومات",
  previousAyah: "الآية السابقة",
  playPause: "تشغيل / إيقاف مؤقت",
  nextAyah: "الآية التالية",
  stop: "إيقاف",
  mute: "كتم الصوت",
  unmute: "إلغاء كتم الصوت",
  volume: "مستوى الصوت",
  playbackSpeed: "سرعة التشغيل",
  repeat: "تكرار",
  shuffle: "عشوائي",
  autoNext: "التالي تلقائياً",

  // Confirms & Headers
  deleteBookmarkConfirm: "هل أنت متأكد من حذف جميع العلامات المرجعية؟",
  deleteNoteConfirm: "هل أنت متأكد من حذف هذه الملاحظة؟",
  page: "صفحة",
  previousSurah: "السورة السابقة",
  nextSurah: "السورة التالية",
  inTheNameOfAllah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",

  // Context Menu, Notes & Error Reports
  editNote: "تعديل الملاحظة",
  addNote: "إضافة ملاحظة",
  foundAnError: "وجدت خطأً",
  reportAnError: "الإبلاغ عن خطأ",
  reportSubmitted: "تم إرسال البلاغ!",
  reportThankYou: "شكراً لإبلاغك. سنراجع المشكلة ونصححها في أقرب وقت.",
  close: "إغلاق",
  targetContext: "السياق المستهدف:",
  errorCategory: "فئة الخطأ:",
  textFont: "النص / الخط",
  audioRecitation: "التلاوة الصوتية",
  otherIssue: "مشكلة أخرى",
  description: "الوصف:",
  describeErrorDetails: "يرجى وصف تفاصيل الخطأ هنا...",
  nameOrEmailOptional: "الاسم أو البريد الإلكتروني (اختياري):",
  yourEmailOrContact: "بريدك الإلكتروني أو وسيلة التواصل...",
  cancel: "إلغاء",
  submitReport: "إرسال البلاغ",
  ayahNotes: "ملاحظات الآية",
  writeCustomNotes: "اكتب ملاحظاتك وتأملاتك الخاصة",
  typeNoteHere: "اكتب ملاحظتك هنا...",
  deleteNote: "حذف الملاحظة",
  saveNote: "حفظ الملاحظة",
  playWordAudio: "تشغيل صوت الكلمة",
  playRecitation: "تشغيل تلاوة الآية",
  playFullAyah: "تشغيل الآية كاملة",
  removeLastReadMark: "إزالة علامة آخر قراءة",
  markAsLastRead: "تحديد كآخر قراءة",
  removeBookmark: "إزالة العلامة المرجعية",
  bookmarkAyah: "إضافة علامة مرجعية للآية",
  shareOnWhatsApp: "مشاركة عبر واتساب",
  shareOnTelegram: "مشاركة عبر تيليجرام",
  shareOnX: "مشاركة عبر X (تويتر)",
  shareOnFacebook: "مشاركة عبر فيسبوك",
  copyAyah: "نسخ الآية",
  copied: "تم النسخ!",
  word: "كلمة:",
  surahProgress: "تقدم السورة"
};
