export const apiManager = {
  // Brand & Navigation
  brandTitle: "واجهة برمجة التطبيقات العامة (API)",
  brandSubtitle: "واجهة REST API مفتوحة المصدر وعالية الأداء للقرآن الكريم",
  badgePublicApi: "واجهة API العامة v1.0",
  freeForeverBadge: "100% مجاناً ومفتوح المصدر",
  showSidebar: "إظهار الشريط الجانبي",
  openMenu: "قائمة API",
  
  // Navigation Tabs
  overviewTab: "نظرة عامة على API",
  explorerTab: "المستكشف التفاعلي",
  codeGenTab: "مُولّد الأكواد",
  schemaTab: "مخطط قاعدة البيانات",
  metricsTab: "مؤشرات وأداء النظام",
  keysTab: "بيئة مفاتيح API",
  
  // Overview Section
  welcomeTitle: "تمكين التطبيقات القرآنية العالمية",
  welcomeDesc: "مرحبًا بكم في مدير واجهات برمجة تطبيقات قرآن عالم المفتوحة. يمكنك الوصول إلى نصوص القرآن كلمة بكلمة، والخطين العثماني والإندوباك، والترجمات، والنقحرة الصوتية، وإحداثيات تخطيط الصفحات والأجزاء، والملفات الصوتية المخزنة في قواعد بيانات سحابية وتخزين الكائنات عالي الأداء.",
  quickStartTitle: "دليل البدء السريع",
  quickStartDesc: "أجرِ أول استدعاء لـ API في ثوانٍ باستخدام طلبات HTTP fetch القياسية. لا يتطلب أي دفع أو بطاقة ائتمان.",
  baseUrlTitle: "رابط النهاية الأساسي للإنتاج (Base URL)",
  baseUrlDesc: "يجب توجيه جميع طلبات واجهة API إلى رابط النهاية التالي:",
  authenticationTitle: "سياسة المصادقة",
  authenticationDesc: "نقاط النهاية العامة للقراءة فقط لا تتطلب أي مصادقة. يمكن إرسال مفاتيح API الاختيارية في ترويسة 'X-API-Key' لزيادة حدود معدل الطلبات.",
  rateLimitTitle: "حدود معدل الطلبات وحجم البيانات",
  rateLimitDesc: "الحد الافتراضي لمعدل الطلبات هو 1000 طلب في الدقيقة لكل عنوان IP مع التخزين المؤقت على شبكة CDN العالمية.",
  corsTitle: "مشاركة الموارد (CORS) والتخزين على الحافة (Edge)",
  corsDesc: "تم ضبط Access-Control-Allow-Origin على '*' في جميع نقاط النهاية. يتم تخزين الاستجابات مؤقتاً في خوادم Edge العالمية لسرعة فائقة.",
  
  // New API Documentation Section
  docSectionTitle: "مواصفات ووثائق واجهة API",
  docSectionSubtitle: "إرشادات شاملة حول تنسيق الرابط الأساسي، وحدود المعدل، وبنية بيانات الاستجابة القياسية لجميع نقاط النهاية العامة.",
  docBaseUrlTitle: "بنية الرابط الأساسي",
  docBaseUrlDesc: "يتم توجيه جميع نقاط النهاية العامة لـ API عبر بروتوكول HTTPS المشفر تحت مسار الإصدار `/api/v1`. يضمن نظام الإصدارات التوافق الكامل مع التطبيقات المستفيدة.",
  docRateLimitTitle: "إرشادات حدود معدل الاستخدام",
  docRateLimitDesc: "يُسمح بالطلبات العامة غير المصادق عليها بما يصل إلى 1,000 طلب في الدقيقة لكل عنوان IP. يعالج التخزين المؤقت على الحافة الاستعلامات المتكررة دون استهلاك الحد المتاح. ترفع المفاتيح المخصصة الحد إلى 10,000 طلب/دقيقة.",
  docResponseFormatTitle: "تنسيق الاستجابة الناجحة القياسي",
  docResponseFormatDesc: "تُرجع جميع الطلبات الناجحة الحالة 200 OK مع غلاف JSON موحد يحتوي على البيانات الوصفية للاستجابة، وإجمالي عدد السجلات، ووقت التنفيذ، ومصفوفة البيانات المطلوبة.",
  docErrorFormatTitle: "تنسيق استجابة الخطأ القياسي",
  docErrorFormatDesc: "عندما يواجه الطلب معاملات غير صالحة أو موارد مفقودة، تُرجع واجهة API بيانات JSON مهيكلة مصحوبة برموز حالة HTTP القياسية 4xx/5xx.",
  
  // Edge API Cache
  cdnCacheTitle: "التخزين المؤقت على الحافة (Edge API Caching)",
  cdnCacheDesc: "تخزين مؤقت مدعوم بتقنية Cache API عالية الأداء (`caches.default`). يتم تقديم الاستعلامات عالية التكرار مباشرة من أكثر من 300 موقع حافة حول العالم في أقل من 15 مللي ثانية دون الضغط على قاعدة البيانات.",
  cdnCacheBadge: "ذاكرة الحافة نشطة",
  cdnCacheTTL: "مدة صلاحية التخزين (TTL): 24 ساعة (`s-maxage=86400`)",

  // Endpoints Info
  availableEndpoints: "نقاط نهاية REST API الأساسية",
  endpointWordsTitle: "بيانات القرآن كلمة بكلمة",
  endpointWordsDesc: "جلب سجلات الكلمات مع التصفية بحسب السورة، الآية، موضع الكلمة، الصفحة، أو أرقام الأجزاء.",
  endpointSurahTitle: "تجميع معلومات وسور القرآن",
  endpointSurahDesc: "استرجاع مجموعات الكلمات الكاملة والبيانات الوصفية لأي سورة (1 إلى 114).",
  endpointSearchTitle: "البحث في النص القرآني الكامل",
  endpointSearchDesc: "البحث في النص العربي (عثماني، إندوباك، إملائي)، أو التراجم الإنجليزية، أو النقحرة الصوتية.",
  endpointStatsTitle: "إحصائيات مجموعة البيانات",
  endpointStatsDesc: "الوصول إلى إجمالي عدد الكلمات، والآيات، وتوزيع الصفحات، ومؤشرات قاعدة البيانات.",
  endpointAudioTitle: "أصول الصوت للكلمات",
  endpointAudioDesc: "روابط البث المباشر والبيانات الوصفية لملفات الصوت MP3 كلمة بكلمة من تخزين الكائنات السحابي.",
  endpointHealthTitle: "صحة وحالة واجهة API",
  endpointHealthDesc: "نقطة نهاية للتحقق اللحظي من اتصال قاعدة البيانات وحالة خوادم الحافة.",

  // Explorer & Tester
  testerTitle: "بيئة الاختبار التفاعلية لـ API",
  testerDesc: "اختبر نقاط النهاية مباشرة من متصفحك. عدّل المعاملات، وأرسل طلبات حية، وافحص رموز الحالة، والترويسات، واستجابات JSON.",
  selectEndpoint: "اختر نقطة النهاية",
  queryParams: "معاملات الاستعلام",
  addParam: "إضافة معامل",
  sendRequest: "إرسال الطلب",
  cancellingRequest: "جاري إلغاء الطلب...",
  requestSuccess: "نجح الطلب",
  requestFailed: "فشل الطلب",
  responseStatus: "رمز الحالة",
  responseTime: "وقت الاستجابة",
  responseSize: "حجم الاستجابة",
  responseHeaders: "ترويسات الاستجابة",
  responseBody: "نص الاستجابة (JSON)",
  copyResponse: "نسخ الاستجابة",
  copiedToast: "تم النسخ إلى الحافظة!",
  clearHistory: "مسح السجل",
  requestHistory: "سجل الاختبارات الأخيرة",
  paramSurah: "رقم السورة (1-114)",
  paramVerse: "رقم الآية",
  paramSearchQuery: "نص البحث",
  paramPage: "صفحة المصحف (1-604)",
  paramJuz: "رقم الجزء (1-30)",
  paramLimit: "حد النتائج (الافتراضي 50)",
  
  // Code Generator
  codeGenTitle: "أمثلة الأكواد بلغات متعددة",
  codeGenDesc: "انسخ على الفور أكواد الطلبات الجاهزة والمختبرة بلغتك البرمجية أو إطار عملك المفضل.",
  selectLanguage: "اختر اللغة / الأداة",
  copyCode: "نسخ الكود البرمجي",
  codeCopiedToast: "تم نسخ الكود البرمجي!",

  // Schema Viewer
  schemaTitle: "مخطط قاعدة بيانات كلمات القرآن (`quran_words`)",
  schemaDesc: "تفصيل شامل لسجلات كلمات القرآن البالغ عددها 88,246 سجلاً والمضمنة في قاعدة بيانات `quranalim`.",
  tableName: "اسم الجدول",
  totalColumns: "إجمالي الأعمدة",
  totalRecords: "إجمالي السجلات",
  columnName: "اسم العمود",
  dataType: "نوع البيانات",
  descriptionHeader: "الوصف",
  sampleValue: "قيمة نموذجية",
  r2BucketTitle: "تخزين الصوت (`bucket`)",
  r2BucketDesc: "يخزن ملفات الصوت MP3 كلمة بكلمة (مثل `wbw/001_001_001.mp3`) المتزامنة مع `quran_words.audio_url`.",

  // Metrics
  metricsTitle: "صحة واجهة API ومؤشرات الشبكة",
  metricsDesc: "مؤشرات تشغيلية حية لدوال Edge، وقاعدة البيانات السحابية، ومخزن الصوتيات.",
  serverStatus: "حالة الخادم",
  operational: "جميع الأنظمة تعمل بكفاءة",
  avgLatency: "متوسط زمن الاستجابة على الحافة",
  totalRequestsToday: "إجمالي طلبات اليوم",
  uptimePercent: "نسبة الجاهزية (30 يومًا)",
  d1Status: "قاعدة البيانات العلائقية",
  r2Status: "مخزن الصوتيات",

  // API Key Playground
  keysTitle: "مُوَلّد مفاتيح الاختبار (Sandbox)",
  keysDesc: "قم بإنشاء مفاتيح مطورين مؤقتة لاختبار ترويسات الطلبات، وحدود المعدل المخصصة، وتطبيقات العميل.",
  generateKey: "توليد مفتاح تجريبي",
  yourApiKey: "مفتاحك التجريبي النشط",
  sandboxKeyNotice: "المفاتيح التجريبية مخصصة لاختبار الترويسات (`X-API-Key: quran_...`) واختبارات تكامل المطورين.",
  rateLimitTier: "فئة حد المعدل",
  requestsPerMin: "10,000 طلب / دقيقة",

  // Common UI
  backHome: "العودة للرئيسية",
  toggleSidebar: "تبديل القائمة",
  closeMenu: "إغلاق القائمة",
  searchPlaceholder: "تصفية نقاط النهاية أو المعاملات...",
  noDataFound: "لم يتم العثور على بيانات للمعايير المحددة.",
  loadingData: "جاري تحميل استجابة API...",
  cancel: "إلغاء",
  reset: "إعادة ضبط",
  refresh: "تحديث البيانات",
  copy: "نسخ"
};
