export const dashboard = {
  quranKareem: "القرآن الكريم",
  welcomeSub: "مرحبًا بك، بوابتك للحكمة الإلهية",
  browseManzil: "تصفح المنازل",
  browseHizb: "تصفح الأحزاب",
  browseJuz: "تصفح الأجزاء",
  browseSurahs: "تصفح السور",
  verseOfTheDay: "آية اليوم",
  lastRead: "آخر ما قُرئ",
  resumeReading: "مواصلة القراءة",
  recitedFrequently: "تُتلى بشكل متكرر",
  tasbihCounter: "عداد التسبيح",
  changeDhikr: "تغيير الذكر",
  tapToIncrease: "اضغط على الدائرة لزيادة العدد",
};
