export const driveApp = {
  driveTitle: "درايف",
  subtitle: "مساحة تخزين سحابية وملفات وسائط",
  accessDeniedTitle: "مطلوب صلاحيات المسؤول",
  accessDeniedDesc: "الوصول إلى درايف مقتصر تمامًا على حسابات المسؤولين. يرجى تسجيل الدخول بحساب مسؤول.",
  loginRequiredTitle: "تسجيل الدخول مطلوب",
  loginRequiredDesc: "يجب أن تكون مسجلاً بصلاحيات المسؤول للوصول إلى إدارة التخزين السحابي.",
  signInBtn: "الذهاب لصفحة تسجيل الدخول",
  demoAdminBtn: "تسجيل الدخول كمسؤول (تجريبي)",
  currentRole: "دور الحساب الحالي",
  userRoleUser: "مستخدم عادي",
  userRoleAdmin: "مسؤول النظام",
  logoutBtn: "تسجيل الخروج",
  switchAccount: "تبديل الحساب",
  myDrive: "ملفاتي (درايف)",
  recentFiles: "أحدث المرفوعات",
  starredFiles: "الملفات المميزة بنجمة",
  trash: "سلة المهملات",
  storageAnalytics: "تحليلات التخزين",
  bucketSettings: "إعدادات درايف",
  searchPlaceholder: "البحث في الملفات والمجلدات والامتدادات...",
  uploadFile: "ملفات",
  newFolder: "مجلد جديد",
  refresh: "تحديث درايف",
  viewGrid: "عرض شبكي",
  viewList: "عرض قائمة",
  filterAll: "جميع العناصر",
  filterImages: "الصور",
  filterAudio: "الصوتيات",
  filterDocuments: "المستندات",
  filterArchives: "الأرشيفات",
  filterOthers: "أخرى",
  name: "الاسم",
  size: "الحجم",
  type: "النوع",
  modified: "تاريخ التعديل",
  actions: "الإجراءات",
  preview: "معاينة",
  download: "تنزيل",
  shareLink: "مشاركة الرابط",
  rename: "إعادة تسمية",
  delete: "حذف",
  restore: "استعادة",
  permanentDelete: "حذف نهائي",
  star: "إضافة نجمة",
  unstar: "إزالة النجمة",
  details: "تفاصيل العنصر",
  totalStorage: "سعة التخزين",
  usedStorage: "المساحة المستخدمة",
  freeStorage: "المساحة المتاحة",
  filesCount: "إجمالي الكائنات",
  foldersCount: "المجلدات",
  uploadModalTitle: "رفع ملف إلى قرآن عالم درايف",
  dropzoneText: "اسحب الملفات وأفلتها هنا، أو انقر للتصفح",
  folderModalTitle: "إنشاء مجلد جديد",
  folderNamePlaceholder: "اسم المجلد (مثل: صوتيات، كتب، نسخ احتياطية)...",
  createBtn: "إنشاء المجلد",
  cancelBtn: "إلغاء",
  noFilesFound: "لم يتم العثور على ملفات في هذا المجلد.",
  emptyTrash: "سلة المهملات فارغة حاليًا.",
  publicUrl: "رابط التخزين العام",
  copiedToast: "تم نسخ رابط التخزين إلى الحافظة!",
  deleteConfirm: "هل تريد نقل هذا العنصر إلى سلة المهملات؟",
  permanentDeleteConfirm: "هل تريد حذف هذا الملف نهائيًا؟ لا يمكن التراجع عن هذا الإجراء.",
  adminBadge: "مسؤول معتمد",
  storageOverview: "نظرة عامة على سعة التخزين",
  fileTypeDistribution: "أنواع الملفات",
  bucketName: "قرآن عالم",
  statusActive: "نشط ومتصل",
  sidebarLockedTitle: "شريط التخزين الجانبي مقفل",
  sidebarLockedDesc: "خيارات التخزين السحابي والبيانات الوصفية وميزات الرفع محمية. يرجى تسجيل الدخول لإلغاء القفل.",
  checkingAuth: "جاري التحقق من المصادقة...",
  redirecting: "جاري التحويل...",
  loginRedirectNotice: "تسجيل الدخول مطلوب للوصول إلى درايف. جاري التحويل إلى صفحة تسجيل الدخول...",
  adminRedirectNotice: "صلاحيات المسؤول مطلوبة للوصول إلى درايف. جاري التحويل إلى الصفحة الرئيسية...",
  copyUrl: "نسخ الرابط",
  close: "إغلاق",
  save: "حفظ",
  itemCount: "عناصر",
  backToHome: "العودة للرئيسية",
  storageStats: "إحصائيات التخزين",
  allFolders: "المجلدات والأدلة",
  allFiles: "جميع الملفات",
  fileExplorerTitle: "مستكشف الملفات",
  folderTreeTitle: "مستكشف الملفات",
  downloadManager: "مدير التنزيلات",
  noFoldersFound: "لم يتم إنشاء مجلدات بعد",
  uploadProgress: "جاري الرفع...",
  uploadManager: "مدير الرفع",
  addUrls: "عناوين URL",
  pasteUrlsLabel: "الصق أو أدخل روابط الملفات (رابط واحد في كل سطر):",
  pasteUrlsPlaceholder: "https://example.com/file1.pdf\nhttps://example.com/image2.jpg\nhttps://example.com/archive3.zip",
  saveAndUpload: "حفظ وبدء الرفع",
  cancel: "إلغاء",
  invalidUrlsNotice: "يرجى إدخال رابط صالح واحد على الأقل.",
  urlsAddedToQueue: "تمت إضافة قائمة الروابط إلى قائمة الانتظار",
  multipleUploads: "مدير الرفع المتعدد",
  quickTools: "أدوات سريعة",
  driveSettings: "إعدادات درايف",
  defaultLayout: "التخطيط الافتراضي",
  autoTrashCleanup: "تفريغ سلة المهملات تلقائيًا (30 يومًا)",
  offlineSync: "تخزين الملفات مؤقتًا دون اتصال",
  storageAlerts: "تنبيهات انخفاض السعة",
  downloadPreference: "وضع جودة التنزيل",
  uploadNotifications: "إشعارات الرفع",
  settingsSaved: "تم حفظ الإعدادات بنجاح",
  uploadSuccess: "تم رفع الملف بنجاح!",
  fileSizeError: "حجم الملف يتجاوز الحد الأقصى المسموح به.",
  folderCreatedSuccess: "تم إنشاء المجلد بنجاح!",
  itemDeletedSuccess: "تم نقل العنصر إلى سلة المهملات.",
  itemRestoredSuccess: "تمت استعادة العنصر بنجاح.",
  itemPermanentDeletedSuccess: "تم حذف العنصر نهائيًا.",
  activityLogs: "سجلات النشاط",
  logTitle: "سجلات نشاط درايف",
  logSubtitle: "سجل تدقيق النظام والتخزين",
  logFilterAll: "جميع الأحداث",
  logFilterFile: "إجراءات الملفات",
  logFilterSystem: "الأمان والنظام",
  clearLogs: "مسح سجل النشاط",
  noLogsFound: "لم يتم تسجيل أي نشاط حتى الآن.",
  logActionUpload: "تم رفع ملف",
  logActionFolder: "تم إنشاء مجلد",
  logActionDelete: "تم النقل إلى المهملات",
  logActionRestore: "تمت استعادة عنصر",
  logActionStar: "تم تمييز ملف بنجمة",
  logActionSystem: "تدقيق أمني",
  logActionAuth: "جلسة مسؤول",
  logsClearedToast: "تم مسح سجلات النشاط بنجاح",
  previousPage: "السابق",
  nextPage: "التالي",
  pageIndicator: "صفحة {current} من {total}",
  itemsPerPage: "عناصر لكل صفحة",
  showingRange: "عرض {start} إلى {end} من أصل {total} عنصر",
  firstPage: "الصفحة الأولى",
  lastPage: "الصفحة الأخيرة",
  fileInfo: "معلومات الملف",
  noFileSelected: "لم يتم تحديد ملف",
  noFileSelectedDesc: "انقر على أي ملف أو مجلد في مساحة التخزين لفحص خصائصه وبياناته الوصفية.",
  path: "مسار الدليل",
  dropToUploadTitle: "أفلت الملفات أو المجلدات للرفع",
  dropToUploadDesc: "سيتم رفع الملفات والمجلدات تلقائيًا إلى",
  dropzoneActive: "أفلت زر الفأرة لبدء الرفع",
  selectFiles: "ملفات",
  selectFolder: "تحديد مجلد",
  uploadFolder: "مجلد",
  dropFilesOrFolder: "اسحب وأفلت الملفات أو المجلدات هنا، أو اختر خيارًا أدناه",
  uploadQueueProgress: "طابور الرفع والتقدم اللحظي",
  clearCompleted: "مسح المكتمل",
  startBatchUpload: "بدء رفع طابور الملفات",
  uploadingQueue: "جاري رفع الملفات...",
  duplicateDetected: "تم اكتشاف ملف مكرر",
  alreadyExistsInFolder: "الملف أو المجلد موجود بالفعل في المسار المحدد",
  skippedDuplicates: "تم تخطي الملفات أو المجلدات المكررة",
  move: "نقل",
  moveToFolder: "نقل إلى مجلد",
  confirmMove: "تأكيد النقل",
  publicAccess: "الوصول العام",
  makePublic: "جعله عاماً",
  publicAccessEnabled: "الوصول العام مفعل",
  publicAccessDisabled: "وصول خاص فقط",
  publicLinkCopied: "تم نسخ الرابط العام إلى الحافظة!",
  liveBulkSync: "مزامنة جماعية حية (R2 إلى قاعدة بيانات D1)",
  syncingD1: "جاري مزامنة سجلات R2 إلى D1...",
  lockFolder: "قفل المجلد",
  unlockFolder: "إلغاء قفل المجلد",
  folderLockedNotice: "هذا المجلد مقفل ومحمي. يرجى إلغاء قفله للوصول إلى المحتوى.",
  folderLockedToast: "تم قفل المجلد بنجاح!",
  folderUnlockedToast: "تم إلغاء قفل المجلد بنجاح!",
  locked: "مقفل",
};
