export const quranReadHome = {
  backHome: "العودة للرئيسية",
  quranReadingHub: "مركز قراءة القرآن",
  brandSubtitle: "المركز الرقمي للقرآن الكريم ورفيق التلاوة",
  digitalQuranReading: "نظام قراءة ومتابعة القرآن الكريم الرقمي",
  toggleSidebar: "تبديل الشريط الجانبي",
  selectLanguage: "اختر اللغة",
  resetProgress: "إعادة ضبط التقدم",
  readingStats: "إحصائيات القراءة الخاصة بك",
  days: "أيام",
  completedSurahs: "السور المكتملة",
  surahsFinished: "نسبة السور المكتملة %",
  totalVersesRead: "إجمالي الآيات المقروءة",
  totalVersesPercent: "نسبة الآيات المقروءة %",
  overallProgress: "التقدم الإجمالي في القرآن الكريم",
  recentlyRead: "قرأت مؤخراً",
  fullyCompleted: "مكتملة بالكامل",
  readingUpToAyah: "القراءة وصلت إلى آية",
  readyToRead: "جاهز للقراءة",
  resetConfirm: "هل أنت أكيد من رغبتك في إعادة ضبط كل تقدم القراءة الخاص بك؟",
  searchPlaceholder: "ابحث عن السورة بالاسم، الرقم أو المعنى...",
  allSurahs: "جميع السور",
  completed: "مكتملة",
  inProgress: "قيد القراءة",
  notStarted: "لم تبدأ",
  verses: "آيات",
  rukus: "ركوعات",
  juz: "أجزاء",
  surahIndexTracking: "فهرس السور والمتابعة",

  // Daily Ayah & Banner
  dailyAyahTitle: "آية اليوم (آية الكرسي)",
  dailyAyahArabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
  dailyAyahTranslation: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
  readSurahContext: "قراءة سورة البقرة",

  // Quick Modes
  quickModesTitle: "ميزات قراءة القرآن والأنماط السريعة",
  mushafMode: "وضع قارئ المصحف",
  mushafModeDesc: "قراءة القرآن الكريم بنمط المصحف الكلاسيكي المكون من 15 سطرًا صفحة بصفحة.",
  audioReciter: "التلاوة الصوتية",
  audioReciterDesc: "الاستماع لكبار القراء مع التظليل المتزامن للآيات.",
  bookmarksNotes: "العلامات المرجعية والمفكرة",
  bookmarksNotesDesc: "الوصول إلى آياتك المحفوظة وملاحظاتك وتأملاتك الشخصية.",
  juzIndex: "فهرس الثلاثين جزءاً",
  juzIndexDesc: "الانتقال المباشر لأي جزء من أجزاء القرآن بنقرة واحدة.",
  statsAnalytics: "تحليلات القراءة",
  statsAnalyticsDesc: "تتبع استمرارية قراءتك والآيات اليومية ومعدل الإنجاز.",
  recommendedSurahs: "السور الموصى بها",
  recommendedSurahsDesc: "روابط سريعة لسور يس، الملك، الكهف، والرحمن.",

  // Juz Quick Grid
  juzGridTitle: "شبكة التنقل بين أجزاء القرآن الثلاثين",
  juzPara: "الجزء",
  startsAtSurah: "يبدأ بسورة",

  // Virtues & Merits
  virtuesTitle: "فضائل وثمرات تلاوة القرآن الكريم",
  virtue1Title: "عشر حسنات بكل حرف",
  virtue1Desc: "قال النبي محمد (ﷺ) أن من قرأ حرفاً من كتاب الله فله به حسنة والحسنة بعشر أمثالها.",
  virtue2Title: "هداية روحية وسكينة",
  virtue2Desc: "القرآن الكريم يسكب الطمأنينة في القلوب وينير الحياة اليومية بالحكمة.",
  virtue3Title: "شفيع لأصحابه يوم القيامة",
  virtue3Desc: "يأتي القرآن يوم القيامة شفيعاً لأصحابه وقرائه المنتظمين.",
  clearInput: "مسح المدخلات",
  recentSearches: "عمليات البحث الأخيرة:",
  removeSearch: "إزالة البحث",
  clearAllHistory: "مسح كافة السجل",
  clearAll: "مسح الكل",
  markAsIncomplete: "تحديد كغير مكتملة",
  markAsCompleted: "تحديد كمكتملة",
  meccan: "مكية",
  medinan: "مدنية",
  noMatchingSurahs: "لم يتم العثور على سور مطابقة.",
  startReading: "ابدأ القراءة",
  surah: "سورة",
  ayah: "آية",
  juzNumber: "رقم الجزء",
  paraJuz: "الجزء",
  sajdahProstration: "سجدة تلاوة",
  yesSajdah: "نعم",
  noSajdah: "لا توجد سجدة في هذه السورة",
  totalWordsEst: "إجمالي الكلمات (تقريبي)",
  totalLettersEst: "إجمالي الحروف (تقريبي)",
  introduction: "مقدمة",
  keyThemes: "المواضيع الرئيسية",
  mainLessons: "الدروس المستفادة",
  virtuesBenefits: "الفيوضات والفضائل",
  periodRevelation: "زمن النزول والسياق التاريخي",
  coreSubjects: "المحاور الأساسية والقضايا العقائدية",
  practicalLessons: "الدروس العملية والحكم للحياة اليومية",
  virtuesSpiritual: "فضائل التلاوة والبركات الروحية",
  reflectionTip: "نصيحة: التدبر العميق في آيات القرآن الكريم هو مصدر الهداية الروحية. هل أنت جاهز؟ عد إلى التلاوة.",
  loadingVerses: "جاري تحميل الآيات القرآنيّة...",
  pleaseWait: "يرجى الانتظار لحظة",
  failedToLoadSurah: "فشل في تحميل بيانات السورة",
  tryAgain: "إعادة المحاولة",
  loadingNextPage: "جاري تحميل الصفحة التالية...",
  backToTop: "العودة إلى الأعلى",
  showSurahSidebar: "إظهار الشريط الجانبي للسور",
  searchVersesInSurah: "البحث عن الآيات في السورة",
  audioError: "فشل في تحميل الصوت للتلاوة.",
  serverError: "خطأ في الاتصال بالخادم.",

  // Options & Tooltips
  quickOptionsMenu: "قائمة الخيارات السريعة",
  closeMenu: "إغلاق القائمة",
  closeRecitation: "إغلاق التلاوة",
  playSurah: "تشغيل السورة",
  searchInSurah: "البحث في السورة",
  changeArabicFont: "تغيير الخط العربي",
  toggleBoldFor: "تبديل الخط العريض",
  changeTextSize: "تغيير حجم النص",
  textSize: "حجم النص",
  changeLineHeight: "تغيير ارتفاع السطر",
  lineHeight: "ارتفاع السطر",
  changeTextAlignment: "تغيير محاذاة النص",
  leftAlign: "محاذاة لليسار",
  centerAlign: "محاذاة للوسط",
  rightAlign: "محاذاة لليمين",
  justifyAlign: "ضبط المحاذاة",
  tooltipSettings: "إعدادات التلميحات",
  tooltipOptions: "خيارات التلميحات",
  translation: "الترجمة",
  chineseTranslation: "الترجمة الصينية",
  chineseSimplified: "المبسطة (简体中文)",
  chineseTraditional: "التقليدية (繁體中文)",
  chinesePinyin: "بينيين (Pinyin)",
  chineseZhuyin: "زويين (Zhuyin)",
  transliteration: "النطق اللاتيني (النقحرة)",
  transliterationStyle: "نمط النقحرة اللاتينية",
  transliterationNormal: "عادي",
  transliterationSyllables: "مقاطع صوتية",
  transliterationSimpleTajweed: "تجويد مبسط",
  transliterationAdvancedTajweed: "تجويد متقدم",
  fontSize: "حجم الخط",

  // Sidebar & Navigation
  juzList: "قائمة الأجزاء",
  hizbList: "قائمة الأحزاب",
  manzilList: "قائمة المنازل",
  sajdahList: "قائمة السجدات",
  rukuList: "قائمة الركوعات",
  pageList: "قائمة الصفحات",
  mushafOrder: "ترتيب المصحف",
  revelationOrder: "ترتيب النزول",
  revelationNo: "رقم النزول",
  surahNo: "السورة",
  hizb: "الحزب",
  manzil: "المنزل",
  sajdah: "السجدة",
  surahList: "قائمة السور",
  surahs: "السور",
  bookmarks: "العلامات المرجعية",
  notes: "الملاحظات",
  options: "الخيارات",
  shortcuts: "اختصارات",
  keyboardShortcuts: "اختصارات لوحة المفاتيح",
  searchShortcutsPlaceholder: "البحث في الاختصارات...",
  shortcutHelpTitle: "اختصارات مفيدة للوحة المفاتيح",
  shortcutHelpDesc: "مفاتيح سريعة للتنقل والتحكم في قارئ القرآن الكريم.",
  categoryAudio: "الصوت والتلاوة",
  categoryNavigation: "التنقل والقراءة",
  categoryInterface: "الواجهة والبحث",
  shortcutPlayPause: "تشغيل / إيقاف الصوت مؤقتاً",
  shortcutNextVerse: "الآية التالية",
  shortcutPrevVerse: "الآية السابقة",
  shortcutSearch: "فتح شريط البحث",
  shortcutToggleSidebar: "تبديل الشريط الجانبي",
  shortcutBookmark: "حفظ الآية بعلامة مرجعية",
  shortcutNextSurah: "السورة التالية",
  shortcutPrevSurah: "السورة السابقة",
  shortcutCloseModal: "إغلاق النوافذ المنبثقة",
  shortcutScrollTop: "الانتقال للأعلى",
  keySpace: "Space",
  keyArrowRight: "→ السهم الأيمن",
  keyArrowLeft: "← السهم الأيسر",
  keyArrowUp: "↑ السهم للأعلى",
  keyArrowDown: "↓ السهم الأسفل",
  keyEsc: "Esc",
  keyCtrlK: "Ctrl + K",
  keyCtrlB: "Ctrl + B",
  keyShiftN: "Shift + N",
  keyShiftP: "Shift + P",
  noShortcutsFound: "لم يتم العثور على اختصارات مطابقة.",
  recitationAndSearch: "التلاوة والبحث",
  textAppearance: "مظهر النص",
  searchSurah: "البحث عن سورة...",
  searchJuz: "البحث في الأجزاء...",
  searchHizb: "البحث في الأحزاب...",
  searchManzil: "البحث في المنازل...",
  searchSajdah: "البحث في السجدات...",
  recent: "حديثاً:",
  clear: "مسح",
  noSurahsFound: "لم يتم العثور على سور",
  noJuzFound: "لم يتم العثور على أجزاء",
  noHizbFound: "لم يتم العثور على أحزاب",
  noManzilFound: "لم يتم العثور على منازل",
  noSajdahFound: "لم يتم العثور على سجدات",
  typeMeccanLabel: "مكية",
  typeMedinanLabel: "مدنية",
  versesLabel: "آيات",
  noBookmarks: "لم يتم حفظ أي علامات مرجعية بعد.",
  ayahNo: "آية ",
  hideSidebar: "إخفاء الشريط الجانبي",
  showSidebar: "إظهار الشريط الجانبي",
  closeSidebar: "إغلاق الشريط الجانبي",
  loadAllPages: "تحميل كافة الصفحات",

  // Search & Playback Controls
  searchVersesPlaceholder: "ابحث عن أي كلمة في هذه السورة...",
  resultsFound: "تم العثور على {count} نتيجة",
  noResultsFound: "لم يتم العثور على نتائج. تحقق من الإملاء أو جرب كلمات أخرى!",
  autoplayNextSurah: "تشغيل السورة التالية تلقائياً",
  repeatMode: "وضع التكرار",
  repeatNone: "إيقاف",
  repeatAyah: "الآية",
  repeatSurah: "السورة",
  repeatAll: "الكل",
  detailsAndInfo: "التفاصيل والمعلومات",
  surahInfo: "معلومات السورة",
  previousAyah: "الآية السابقة",
  playPause: "تشغيل / إيقاف مؤقت",
  nextAyah: "الآية التالية",
  stop: "إيقاف",
  mute: "كتم الصوت",
  unmute: "إلغاء كتم الصوت",
  volume: "مستوى الصوت",
  playbackSpeed: "سرعة التشغيل",
  repeat: "تكرار",
  shuffle: "عشوائي",
  autoNext: "التالي تلقائياً",

  // Confirms & Headers
  deleteBookmarkConfirm: "هل أنت متأكد من حذف جميع العلامات المرجعية؟",
  deleteNoteConfirm: "هل أنت متأكد من حذف هذه الملاحظة؟",
  page: "صفحة",
  previousSurah: "السورة السابقة",
  nextSurah: "السورة التالية",
  inTheNameOfAllah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",

  // Context Menu, Notes & Error Reports
  editNote: "تعديل الملاحظة",
  addNote: "إضافة ملاحظة",
  foundAnError: "وجدت خطأً",
  reportAnError: "الإبلاغ عن خطأ",
  reportSubmitted: "تم إرسال البلاغ!",
  reportThankYou: "شكراً لإبلاغك. سنراجع المشكلة ونصححها في أقرب وقت.",
  close: "إغلاق",
  targetContext: "السياق المستهدف:",
  errorCategory: "فئة الخطأ:",
  textFont: "النص / الخط",
  audioRecitation: "التلاوة الصوتية",
  otherIssue: "مشكلة أخرى",
  description: "الوصف:",
  describeErrorDetails: "يرجى وصف تفاصيل الخطأ هنا...",
  nameOrEmailOptional: "الاسم أو البريد الإلكتروني (اختياري):",
  yourEmailOrContact: "بريدك الإلكتروني أو وسيلة التواصل...",
  cancel: "إلغاء",
  submitReport: "إرسال البلاغ",
  ayahNotes: "ملاحظات الآية",
  writeCustomNotes: "اكتب ملاحظاتك وتأملاتك الخاصة",
  typeNoteHere: "اكتب ملاحظتك هنا...",
  deleteNote: "حذف الملاحظة",
  saveNote: "حفظ الملاحظة",
  playWordAudio: "تشغيل صوت الكلمة",
  playRecitation: "تشغيل تلاوة الآية",
  playFullAyah: "تشغيل الآية كاملة",
  removeLastReadMark: "إزالة علامة آخر قراءة",
  markAsLastRead: "تحديد كآخر قراءة",
  removeBookmark: "إزالة العلامة المرجعية",
  bookmarkAyah: "إضافة علامة مرجعية للآية",
  shareOnWhatsApp: "مشاركة عبر واتساب",
  shareOnTelegram: "مشاركة عبر تيليجرام",
  shareOnX: "مشاركة عبر X (تويتر)",
  shareOnFacebook: "مشاركة عبر فيسبوك",
  copyAyah: "نسخ الآية",
  copied: "تم النسخ!",
  word: "كلمة:",
  surahProgress: "تقدم السورة",
  inQuran: "في القرآن",
  inSurah: "في السورة",
  times: "مرات",
  allWords: "الكل",
  uniqueWords: "الفريدة",
  groups: "المجموعات",
  previous: "السابق",
  next: "التالي",
  of: "من",
  playAudio: "تشغيل الصوت",
  backToSurah: "العودة إلى التلاوة",

  // Reciter & Qaris
  reciter: "القارئ",
  selectReciter: "اختر القارئ",
  searchReciters: "البحث عن القراء بالاسم أو الرواية...",
  qiratStyle: "رواية القراءة",
  defaultReciter: "الشيخ مشاري راشد العفاسي (حفص - مرتل)",
  allReciters: "جميع القراء (20)",

  // Audio Sync Section
  audioSyncTitle: "مزامنة ملفات الصوت بقاعدة البيانات (quran_audio_files)",
  audioSyncSubtitle: "حفظ الملفات الصوتية الكاملة وفترات توقيت الكلمات في قاعدة بيانات D1 'quranalim' (الجدول: quran_audio_files)",
  syncAllSurahsBtn: "مزامنة جميع السور الـ 114 مع قاعدة البيانات",
  syncingDbProgress: "جاري مزامنة الملفات الصوتية مع قاعدة البيانات...",
  syncCompletedSuccess: "تمت مزامنة الملفات الصوتية بنجاح إلى جدول 'quran_audio_files' في قاعدة بيانات 'quranalim'!",
  dbTableStatus: "حالة جدول D1: quran_audio_files",
  syncedRecords: "السجلات المتزامنة في قاعدة البيانات:",
  dbBindingName: "رابط قاعدة بيانات D1: DB (quranalim)"
};
