export const apiManager = {
  // Brand & Navigation
  brandTitle: "Public API",
  brandSubtitle: "High-Performance Open Source Al-Quran REST API",
  badgePublicApi: "Public API v1.0",
  freeForeverBadge: "100% Free & Open Source",
  showSidebar: "Show Sidebar",
  openMenu: "API Menu",
  
  // Navigation Tabs
  overviewTab: "API Overview",
  explorerTab: "Interactive Explorer",
  codeGenTab: "Code Generator",
  schemaTab: "Database Schema",
  metricsTab: "System Metrics",
  keysTab: "API Keys Playground",
  
  // Overview Section
  welcomeTitle: "Empowering Global Quranic Applications",
  welcomeDesc: "Welcome to the QuranAlim Open API Manager. Access word-by-word Quranic texts, Uthmani/IndoPak scripts, translations, transliterations, page/juz layout coordinates, and word-by-word audio files stored in high-performance cloud databases and object storage.",
  quickStartTitle: "Quick Start Guide",
  quickStartDesc: "Make your first API call in seconds using standard HTTP fetch requests. No payment or credit card required.",
  baseUrlTitle: "Production Base URL",
  baseUrlDesc: "All API requests should be addressed to the following endpoint URL:",
  authenticationTitle: "Authentication Policy",
  authenticationDesc: "Public read-only endpoints require no authentication. Optional API keys can be passed in 'X-API-Key' header for higher rate limits.",
  rateLimitTitle: "Rate Limiting & Bandwidth",
  rateLimitDesc: "Default rate limit is 1000 requests per minute per IP address with global CDN edge caching.",
  corsTitle: "CORS & Edge Caching",
  corsDesc: "Access-Control-Allow-Origin is set to '*' on all endpoints. Responses are cached on global Edge CDN locations for ultra-fast latency.",
  
  // New API Documentation Section
  docSectionTitle: "API Specifications & Documentation",
  docSectionSubtitle: "Comprehensive guidelines on base URL formatting, rate limits, and standard response payload structures for all public endpoints.",
  docBaseUrlTitle: "Base URL Structure",
  docBaseUrlDesc: "All public API endpoints are routed over HTTPS under the `/api/v1` versioned namespace. Versioning guarantees backwards compatibility for client applications.",
  docRateLimitTitle: "Rate Limiting Guidelines",
  docRateLimitDesc: "Public unauthenticated requests are permitted up to 1,000 requests per minute per IP address. Edge caching handles repeated queries without depleting rate capacity. Custom keys increase capacity to 10,000 req/min.",
  docResponseFormatTitle: "Standard Success Response Format",
  docResponseFormatDesc: "All successful requests return HTTP status 200 OK with a uniform JSON envelope containing response metadata, total record counts, execution time, and requested data array.",
  docErrorFormatTitle: "Standard Error Response Format",
  docErrorFormatDesc: "When a request encounters invalid parameters or missing resources, the API returns a structured JSON payload accompanied by standard HTTP 4xx/5xx status codes.",
  
  // Edge API Cache
  cdnCacheTitle: "Edge API Caching",
  cdnCacheDesc: "Edge response caching powered by High-Performance Cache API (`caches.default`). High-frequency queries are served directly from 300+ Edge locations worldwide in < 15ms without hitting the database.",
  cdnCacheBadge: "Edge Cache Active",
  cdnCacheTTL: "Edge TTL: 24 Hours (`s-maxage=86400`)",

  // Endpoints Info
  availableEndpoints: "Core REST API Endpoints",
  endpointWordsTitle: "Word-by-Word Quran Data",
  endpointWordsDesc: "Fetch word records filtered by surah, verse, word position, page, or juz numbers.",
  endpointSurahTitle: "Surah Aggregation & Info",
  endpointSurahDesc: "Retrieve complete word collections and metadata for any Surah (1 to 114).",
  endpointSearchTitle: "Full-Text Quran Search",
  endpointSearchDesc: "Search through Arabic text (Uthmani, IndoPak, Imlaei), English translations, or transliterations.",
  endpointStatsTitle: "Dataset Statistics",
  endpointStatsDesc: "Access total word counts, verse totals, page distributions, and database metrics.",
  endpointAudioTitle: "Word Audio Assets",
  endpointAudioDesc: "Direct stream links and metadata for word-by-word audio MP3 files from cloud object storage.",
  endpointHealthTitle: "API Health & Status",
  endpointHealthDesc: "Real-time health check endpoint indicating database connectivity and edge status.",

  // Explorer & Tester
  testerTitle: "Interactive API Playground",
  testerDesc: "Test endpoints directly from your browser. Adjust parameters, send live requests, inspect status codes, headers, and JSON responses.",
  selectEndpoint: "Select Endpoint",
  queryParams: "Query Parameters",
  addParam: "Add Parameter",
  sendRequest: "Send Request",
  cancellingRequest: "Cancelling Request...",
  requestSuccess: "Request Succeeded",
  requestFailed: "Request Failed",
  responseStatus: "Status Code",
  responseTime: "Response Time",
  responseSize: "Response Size",
  responseHeaders: "Response Headers",
  responseBody: "Response Body (JSON)",
  copyResponse: "Copy Response",
  copiedToast: "Copied to clipboard!",
  clearHistory: "Clear History",
  requestHistory: "Recent Test History",
  paramSurah: "Surah Number (1-114)",
  paramVerse: "Verse / Ayah Number",
  paramSearchQuery: "Search Text Query",
  paramPage: "Mushaf Page (1-604)",
  paramJuz: "Juz / Para Number (1-30)",
  paramLimit: "Result Limit (Default 50)",
  
  // Code Generator
  codeGenTitle: "Multi-Language Code Snippets",
  codeGenDesc: "Instantly copy battle-tested request code in your preferred programming language or framework.",
  selectLanguage: "Select Language / Tool",
  copyCode: "Copy Code Snippet",
  codeCopiedToast: "Code snippet copied!",

  // Schema Viewer
  schemaTitle: "Quran Words Database Schema (`quran_words`)",
  schemaDesc: "Detailed breakdown of the 88,246 Quranic word records contained in the `quranalim` database.",
  tableName: "Table Name",
  totalColumns: "Total Columns",
  totalRecords: "Total Records",
  columnName: "Column Name",
  dataType: "Data Type",
  descriptionHeader: "Description",
  sampleValue: "Sample Value",
  r2BucketTitle: "Audio Storage (`bucket`)",
  r2BucketDesc: "Stores word-by-word audio MP3 files (e.g., `wbw/001_001_001.mp3`) synced with `quran_words.audio_url`.",

  // Metrics
  metricsTitle: "API Health & Network Metrics",
  metricsDesc: "Live operational metrics for Edge Functions, Cloud Database, and Audio Storage.",
  serverStatus: "Server Status",
  operational: "All Systems Operational",
  avgLatency: "Average Edge Latency",
  totalRequestsToday: "Total Requests Today",
  uptimePercent: "Uptime (30 Days)",
  d1Status: "Relational Database",
  r2Status: "Audio Storage Bucket",

  // API Key Playground
  keysTitle: "Sandbox API Key Generator",
  keysDesc: "Generate temporary developer keys to test request headers, custom rate limits, and client applications.",
  generateKey: "Generate Sandbox Key",
  yourApiKey: "Your Active Sandbox Key",
  sandboxKeyNotice: "Sandbox keys are intended for header testing (`X-API-Key: quran_...`) and developer integration testing.",
  rateLimitTier: "Rate Limit Tier",
  requestsPerMin: "10,000 requests / minute",

  // Common UI
  backHome: "Back to Home",
  toggleSidebar: "Toggle Menu",
  closeMenu: "Close Menu",
  searchPlaceholder: "Filter endpoints or parameters...",
  noDataFound: "No data found for the given criteria.",
  loadingData: "Loading API response...",
  cancel: "Cancel",
  reset: "Reset",
  refresh: "Refresh Data",
  copy: "Copy"
};
