export const apps = {
  loading: {
    msg: "Loading translations, please wait...",
    failed: "Failed to Load Language Pack",
    retry: "Retry Loading",
    pack: "Language Pack"
  },
  pwa: {
    title: "Install QuranAlim App",
    desc: "Add QuranAlim to your home screen for rapid, offline-friendly access and an immersive standalone layout.",
    installBtn: "Install App",
    iosGuideTitle: "iOS App Installation",
    iosGuideDesc: "To install QuranAlim on your iOS device: tap the Share button in Safari, scroll down, and select 'Add to Home Screen'.",
    close: "Close",
    howToInstall: "How to Install App",
    manualStepsDesc: "To install QuranAlim on your phone or computer:",
    step1: "Open your browser's menu (usually top-right three dots).",
    step2: "Select 'Install App' or 'Add to Home Screen'.",
    step3: "Or click the Install icon in your browser's address bar.",
    iosStep1: "1. Tap the 'Share' icon in Safari browser.",
    iosStep2: "2. Scroll down and choose 'Add to Home Screen'."
  },
  titles: {
    home: "Home - Quran Alim",
    login: "Login - Quran Alim",
    signup: "Sign Up - Quran Alim",
    forgotPassword: "Forgot Password - Quran Alim",
    resetPassword: "Reset Password - Quran Alim",
    dashboard: "Dashboard - Quran Alim",
    hadith: "Hadith & Sunnah - Quran Alim",
    wuduGuide: "Wudu Guide - Islamic Fiqh - Quran Alim",
    salahGuide: "Salah Guide - Islamic Fiqh - Quran Alim",
    fatawa: "Shariah Ask & Fatawa - Islamic Fiqh - Quran Alim",
    zakat: "Zakat Calculator - Islamic Fiqh - Quran Alim",
    fiqh: "Islamic Fiqh - Quran Alim",
    library: "Islamic Library - Quran Alim",
    libraryBook: "{book} - Library - Quran Alim",
    libraryChapter: "{chapter} - {book} - Library - Quran Alim",
    tools: "Islamic Tools - Quran Alim",
    about: "About Us - Quran Alim",
    contact: "Contact Us - Quran Alim",
    donate: "Support & Donate - Quran Alim",
    terms: "Terms & Conditions - Quran Alim",
    privacy: "Privacy Policy - Quran Alim",
    tos: "Terms of Service - Quran Alim",
    disclaimer: "Disclaimer - Quran Alim",
    quranDashboard: "Quran Dashboard - Quran Alim",
    allSurahs: "All Quran Surahs - Quran Alim",
    allJuz: "All Quran Juz - Quran Alim",
    allHizb: "All Quran Hizb - Quran Alim",
    allManzil: "All Quran Manzil - Quran Alim",
    surah: "Surah {surah} - Quran Alim",
    quranDefault: "Holy Quran - Quran Alim"
  }
};
