export const driveApp = {
  driveTitle: "Drive",
  subtitle: "Drive Cloud & Media Storage",
  accessDeniedTitle: "Admin Access Required",
  accessDeniedDesc: "Access to Drive is strictly restricted to Administrator accounts. Please sign in with an Admin account.",
  loginRequiredTitle: "Sign In Required",
  loginRequiredDesc: "You must be signed in with Administrator privileges to access Cloud Storage management.",
  signInBtn: "Go to Login Page",
  demoAdminBtn: "Sign In as Admin (Demo)",
  currentRole: "Current Account Role",
  userRoleUser: "Standard User",
  userRoleAdmin: "Administrator",
  logoutBtn: "Sign Out",
  switchAccount: "Switch Account",
  myDrive: "My Drive",
  recentFiles: "Recent Uploads",
  starredFiles: "Starred Files",
  trash: "Trash Bin",
  storageAnalytics: "Storage Analytics",
  bucketSettings: "Drive Configuration",
  searchPlaceholder: "Search files, directories, extensions...",
  uploadFile: "Files",
  newFolder: "New Folder",
  refresh: "Refresh Drive",
  viewGrid: "Grid View",
  viewList: "List View",
  filterAll: "All Items",
  filterImages: "Images",
  filterAudio: "Audio",
  filterDocuments: "Documents",
  filterArchives: "Archives",
  filterOthers: "Others",
  name: "Name",
  size: "Size",
  type: "Type",
  modified: "Modified",
  actions: "Actions",
  preview: "Preview",
  download: "Download",
  shareLink: "Share Link",
  rename: "Rename",
  delete: "Delete",
  restore: "Restore",
  permanentDelete: "Delete Permanently",
  star: "Add Star",
  unstar: "Remove Star",
  details: "Item Details",
  totalStorage: "Storage Capacity",
  usedStorage: "Used Storage",
  freeStorage: "Available Space",
  filesCount: "Total Objects",
  foldersCount: "Directories",
  uploadModalTitle: "Upload File to Quran Alim Drive",
  dropzoneText: "Drag and drop files here, or click to browse",
  folderModalTitle: "Create New Directory",
  folderNamePlaceholder: "Folder name (e.g., Audio, Books, Backups)...",
  createBtn: "Create Directory",
  cancelBtn: "Cancel",
  noFilesFound: "No files found in this directory.",
  emptyTrash: "Trash bin is currently empty.",
  publicUrl: "Public Storage Link",
  copiedToast: "Storage link copied to clipboard!",
  deleteConfirm: "Move this item to Trash?",
  permanentDeleteConfirm: "Permanently delete this file? This action cannot be undone.",
  adminBadge: "Admin Verified",
  storageOverview: "Storage Capacity Overview",
  fileTypeDistribution: "File Types",
  bucketName: "Quran Alim",
  statusActive: "Active & Connected",
  sidebarLockedTitle: "Storage Sidebar Locked",
  sidebarLockedDesc: "Cloud Storage options, metadata, and upload features are protected. Please sign in to unlock.",
  checkingAuth: "Checking Authentication...",
  redirecting: "Redirecting...",
  loginRedirectNotice: "Sign in required to access Drive. Redirecting to login page...",
  adminRedirectNotice: "Admin access required for Drive. Redirecting to home page...",
  copyUrl: "Copy URL",
  close: "Close",
  save: "Save",
  itemCount: "Items",
  backToHome: "Back to Home",
  storageStats: "Storage Stats",
  allFolders: "Folders & Directories",
  allFiles: "All Files",
  fileExplorerTitle: "File Explorer",
  folderTreeTitle: "File Explorer",
  downloadManager: "Download Manager",
  noFoldersFound: "No folders created yet",
  uploadProgress: "Uploading...",
  uploadManager: "Upload Manager",
  addUrls: "Urls",
  pasteUrlsLabel: "Paste or enter file URLs (one per line):",
  pasteUrlsPlaceholder: "https://example.com/file1.pdf\nhttps://example.com/image2.jpg\nhttps://example.com/archive3.zip",
  saveAndUpload: "Save & Start Upload",
  cancel: "Cancel",
  invalidUrlsNotice: "Please enter at least one valid URL.",
  urlsAddedToQueue: "URL batch added to queue",
  multipleUploads: "Multiple Upload Manager",
  quickTools: "Quick Tools",
  driveSettings: "Drive Settings",
  defaultLayout: "Default Layout",
  autoTrashCleanup: "Auto-Purge Trash (30 Days)",
  offlineSync: "Offline File Cache",
  storageAlerts: "Low Capacity Alerts",
  downloadPreference: "Download Quality Mode",
  uploadNotifications: "Upload Notifications",
  settingsSaved: "Settings saved successfully",
  uploadSuccess: "File uploaded successfully!",
  fileSizeError: "File exceeds max upload size limit.",
  folderCreatedSuccess: "Folder created successfully!",
  itemDeletedSuccess: "Item moved to trash.",
  itemRestoredSuccess: "Item restored successfully.",
  itemPermanentDeletedSuccess: "Item permanently deleted.",
  activityLogs: "Activity Logs",
  logTitle: "Drive Activity Logs",
  logSubtitle: "System & Storage Audit Trail",
  logFilterAll: "All Events",
  logFilterFile: "File Actions",
  logFilterSystem: "System & Security",
  clearLogs: "Clear Log History",
  noLogsFound: "No activity logs recorded yet.",
  logActionUpload: "File Uploaded",
  logActionFolder: "Folder Created",
  logActionDelete: "Moved to Trash",
  logActionRestore: "Restored Item",
  logActionStar: "Starred File",
  logActionSystem: "Security Audit",
  logActionAuth: "Admin Session",
  logsClearedToast: "Activity logs cleared successfully",
  previousPage: "Previous",
  nextPage: "Next",
  pageIndicator: "Page {current} of {total}",
  itemsPerPage: "Items per page",
  showingRange: "Showing {start} to {end} of {total} items",
  firstPage: "First Page",
  lastPage: "Last Page",
  fileInfo: "File Information",
  noFileSelected: "No File Selected",
  noFileSelectedDesc: "Click on any file or folder in the storage view to inspect its properties and metadata.",
  path: "Directory Location",
  dropToUploadTitle: "Drop Files or Folders to Upload",
  dropToUploadDesc: "Files & folders will be automatically uploaded to",
  dropzoneActive: "Release mouse to drop and upload",
  selectFiles: "Files",
  selectFolder: "Select Folder",
  uploadFolder: "Folder",
  dropFilesOrFolder: "Drag & drop files or folders here, or choose an option below",
  uploadQueueProgress: "Upload Queue & Real-time Progress",
  clearCompleted: "Clear Completed",
  startBatchUpload: "Start Upload Queue",
  uploadingQueue: "Uploading Queue...",
  duplicateDetected: "Duplicate Detected",
  alreadyExistsInFolder: "File or folder already exists in target directory",
  skippedDuplicates: "Skipped duplicate file(s) or folder(s)",
  move: "Move",
  moveToFolder: "Move to Folder",
  confirmMove: "Confirm Move",
  publicAccess: "Public Access",
  makePublic: "Make Public",
  publicAccessEnabled: "Public Access Active",
  publicAccessDisabled: "Private Access Only",
  publicLinkCopied: "Public link copied to clipboard!",
  liveBulkSync: "Live Bulk Sync (R2 to D1 Database)",
  syncingD1: "Synchronizing R2 records to D1...",
  lockFolder: "Lock Folder",
  unlockFolder: "Unlock Folder",
  folderLockedNotice: "This folder is locked and protected. Unlock it to access content.",
  folderLockedToast: "Folder locked successfully!",
  folderUnlockedToast: "Folder unlocked successfully!",
  locked: "Locked",
};
