export const quranReadHome = {
  backHome: "Back Home",
  quranReadingHub: "Quran Reading Hub",
  brandSubtitle: "Digital Al-Quran Hub & Recitation Companion",
  digitalQuranReading: "Digital Quran Reading & Tracking System",
  toggleSidebar: "Toggle Sidebar",
  selectLanguage: "Select Language",
  resetProgress: "Reset Progress",
  readingStats: "Your Reading Statistics",
  days: "Days",
  completedSurahs: "Completed Surahs",
  surahsFinished: "Surahs Finished %",
  totalVersesRead: "Total Verses Read",
  totalVersesPercent: "Total Verses %",
  overallProgress: "Overall Al-Quran Progress",
  recentlyRead: "Recently Read",
  fullyCompleted: "Fully Completed",
  readingUpToAyah: "Reading up to Ayah",
  readyToRead: "Ready to Read",
  resetConfirm: "Are you sure you want to reset all your reading progress?",
  searchPlaceholder: "Search Surah by name, ID or meaning...",
  allSurahs: "All Surahs",
  completed: "Completed",
  inProgress: "In Progress",
  notStarted: "Not Started",
  verses: "Verses",
  rukus: "Rukus",
  juz: "Juz",
  surahIndexTracking: "Surah Index & Tracking",

  // Daily Ayah & Banner
  dailyAyahTitle: "Verse of the Day (Ayat-ul-Kursi)",
  dailyAyahArabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
  dailyAyahTranslation: "Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth.",
  readSurahContext: "Read Surah Al-Baqarah",

  // Quick Modes
  quickModesTitle: "Quran Reading Features & Quick Modes",
  mushafMode: "Mushaf Reader Mode",
  mushafModeDesc: "Read full 15-line classical style digital Quran page by page.",
  audioReciter: "Audio Recitation",
  audioReciterDesc: "Listen to world-renowned Qaris with synchronized ayah highlighting.",
  bookmarksNotes: "Bookmarks & Journal",
  bookmarksNotesDesc: "Access your saved ayahs, personal notes, and study reflections.",
  juzIndex: "30 Juz / Para Index",
  juzIndexDesc: "Directly jump to any of the 30 Juz/Paras with one click.",
  statsAnalytics: "Reading Analytics",
  statsAnalyticsDesc: "Track your reading streak, daily verses, and completion rate.",
  recommendedSurahs: "Recommended Surahs",
  recommendedSurahsDesc: "Quick links to Surah Yaseen, Al-Mulk, Al-Kahf, and Ar-Rahman.",

  // Juz Quick Grid
  juzGridTitle: "30 Juz / Para Navigation Grid",
  juzPara: "Juz / Para",
  startsAtSurah: "Starts at",

  // Virtues & Merits
  virtuesTitle: "Virtues & Spiritual Benefits of Quran Recitation",
  virtue1Title: "10 Rewards Per Letter",
  virtue1Desc: "Prophet Muhammad (ﷺ) said reciting every single letter of the Holy Quran brings 10 good deeds.",
  virtue2Title: "Spiritual Guidance & Peace",
  virtue2Desc: "The Holy Quran brings tranquility to hearts and lights up your daily life with wisdom.",
  virtue3Title: "Intercession on Judgment Day",
  virtue3Desc: "The Quran will act as an intercessor for its regular reciters on the Day of Resurrection.",
  clearInput: "Clear input",
  recentSearches: "Recent Searches:",
  removeSearch: "Remove search",
  clearAllHistory: "Clear all history",
  clearAll: "Clear all",
  markAsIncomplete: "Mark as Incomplete",
  markAsCompleted: "Mark as Completed",
  meccan: "Meccan",
  medinan: "Medinan",
  noMatchingSurahs: "No matching Surahs found.",
  startReading: "Start Reading",
  surah: "Surah",
  ayah: "Ayah",
  juzNumber: "Juz Number",
  paraJuz: "Para / Juz",
  sajdahProstration: "Sajdah (Prostration)",
  yesSajdah: "Yes",
  noSajdah: "No Sajdah in this Surah",
  totalWordsEst: "Total Words (Est.)",
  totalLettersEst: "Total Letters (Est.)",
  introduction: "Introduction",
  keyThemes: "Key Themes",
  mainLessons: "Main Lessons",
  virtuesBenefits: "Virtues & Benefits",
  periodRevelation: "Period of Revelation & Historical Context",
  coreSubjects: "Core Subjects and Key Theological Themes",
  practicalLessons: "Practical Lessons & Wisdom for Everyday Life",
  virtuesSpiritual: "Virtues & Spiritual Merits of Recitation",
  reflectionTip: "Tip: Reflecting deeply on the message of the Quran is a source of spiritual guidance. Ready? Head back to recitation.",
  loadingVerses: "Loading Quranic verses...",
  pleaseWait: "Please wait a moment",
  failedToLoadSurah: "Failed to load Surah data",
  tryAgain: "Try Again",
  loadingNextPage: "Loading next page...",
  backToTop: "Back to Top",
  showSurahSidebar: "Show Surah Sidebar",
  searchVersesInSurah: "Search Verses in Surah",
  audioError: "Failed to load recitation audio.",
  serverError: "Error connecting to server.",

  // Options & Tooltips
  quickOptionsMenu: "Quick Options Menu",
  closeMenu: "Close Menu",
  closeRecitation: "Close Recitation",
  playSurah: "Play Surah",
  searchInSurah: "Search in Surah",
  changeArabicFont: "Change Arabic Font",
  toggleBoldFor: "Toggle Bold for",
  changeTextSize: "Change Text Size",
  textSize: "Text Size",
  changeLineHeight: "Change Line Height",
  lineHeight: "Line Height",
  changeTextAlignment: "Change Text Alignment",
  leftAlign: "Left Align",
  centerAlign: "Center Align",
  rightAlign: "Right Align",
  justifyAlign: "Justify Align",
  tooltipSettings: "Tooltip Settings",
  tooltipOptions: "Tooltip Options",
  translation: "Translation",
  chineseTranslation: "Chinese Translation",
  chineseSimplified: "Simplified (简体中文)",
  chineseTraditional: "Traditional (繁體中文)",
  chinesePinyin: "Pinyin (拼音)",
  chineseZhuyin: "Zhuyin (注音)",
  transliteration: "Transliteration",
  transliterationStyle: "Transliteration Style",
  transliterationNormal: "Normal",
  transliterationSyllables: "Syllables",
  transliterationSimpleTajweed: "Simple Tajweed",
  transliterationAdvancedTajweed: "Advanced Tajweed",
  fontSize: "Font Size",

  // Sidebar & Navigation
  surahList: "Surah List",
  juzList: "Juz List",
  hizbList: "Hizb List",
  manzilList: "Manzil List",
  sajdahList: "Sajdah List",
  rukuList: "Ruku List",
  pageList: "Page List",
  mushafOrder: "Mushaf Order",
  revelationOrder: "Revelation Order",
  revelationNo: "Rev.",
  surahNo: "Surah",
  hizb: "Hizb",
  manzil: "Manzil",
  sajdah: "Sajdah",
  surahs: "Surahs",
  bookmarks: "Bookmarks",
  notes: "Notes",
  options: "Options",
  shortcuts: "Shortcuts",
  keyboardShortcuts: "Keyboard Shortcuts",
  searchShortcutsPlaceholder: "Search shortcuts...",
  shortcutHelpTitle: "Useful Keyboard Shortcuts",
  shortcutHelpDesc: "Quick navigation and control keybindings for Al-Quran reader.",
  categoryAudio: "Audio & Recitation",
  categoryNavigation: "Navigation & Reading",
  categoryInterface: "Interface & Search",
  shortcutPlayPause: "Play / Pause Audio",
  shortcutNextVerse: "Next Verse",
  shortcutPrevVerse: "Previous Verse",
  shortcutSearch: "Open Search Bar",
  shortcutToggleSidebar: "Toggle Sidebar",
  shortcutBookmark: "Bookmark Verse",
  shortcutNextSurah: "Next Surah",
  shortcutPrevSurah: "Previous Surah",
  shortcutCloseModal: "Close Overlays",
  shortcutScrollTop: "Scroll to Top",
  keySpace: "Space",
  keyArrowRight: "→ Right Arrow",
  keyArrowLeft: "← Left Arrow",
  keyArrowUp: "↑ Up Arrow",
  keyArrowDown: "↓ Down Arrow",
  keyEsc: "Esc",
  keyCtrlK: "Ctrl + K",
  keyCtrlB: "Ctrl + B",
  keyShiftN: "Shift + N",
  keyShiftP: "Shift + P",
  noShortcutsFound: "No matching shortcuts found.",
  recitationAndSearch: "Recitation & Search",
  textAppearance: "Text Appearance",
  searchSurah: "Search Surah...",
  searchJuz: "Search Juz...",
  searchHizb: "Search Hizb...",
  searchManzil: "Search Manzil...",
  searchSajdah: "Search Sajdah...",
  recent: "Recent:",
  clear: "Clear",
  noSurahsFound: "No Surahs Found",
  noJuzFound: "No Juz Found",
  noHizbFound: "No Hizb Found",
  noManzilFound: "No Manzil Found",
  noSajdahFound: "No Sajdah Found",
  typeMeccanLabel: "Meccan",
  typeMedinanLabel: "Medinan",
  versesLabel: "Verses",
  noBookmarks: "No bookmarks saved yet.",
  ayahNo: "Ayah ",
  hideSidebar: "Hide Sidebar",
  showSidebar: "Show Sidebar",
  closeSidebar: "Close Sidebar",
  loadAllPages: "Load All Pages",

  // Search & Playback Controls
  searchVersesPlaceholder: "Search any word in this Surah...",
  resultsFound: "Found {count} result(s)",
  noResultsFound: "No results found. Double-check your spelling or try search terms!",
  autoplayNextSurah: "Autoplay Next Surah",
  repeatMode: "Repeat Mode",
  repeatNone: "Off",
  repeatAyah: "Ayah",
  repeatSurah: "Surah",
  repeatAll: "All",
  detailsAndInfo: "Details & Info",
  surahInfo: "Surah Info",
  previousAyah: "Previous Ayah",
  playPause: "Play / Pause",
  nextAyah: "Next Ayah",
  stop: "Stop",
  mute: "Mute",
  unmute: "Unmute",
  volume: "Volume",
  playbackSpeed: "Playback Speed",
  repeat: "Repeat",
  shuffle: "Shuffle",
  autoNext: "Auto-Next",

  // Confirms & Headers
  deleteBookmarkConfirm: "Are you sure you want to delete all bookmarks?",
  deleteNoteConfirm: "Are you sure you want to delete this note?",
  page: "Page",
  previousSurah: "Previous Surah",
  nextSurah: "Next Surah",
  inTheNameOfAllah: "In the name of Allah, the Beneficent, the Merciful",

  // Context Menu, Notes & Error Reports
  editNote: "Edit Note",
  addNote: "Add Note",
  foundAnError: "Found an Error",
  reportAnError: "Report an Error",
  reportSubmitted: "Report Submitted!",
  reportThankYou: "Thank you for reporting. We will review and correct the issue promptly.",
  close: "Close",
  targetContext: "Target Context:",
  errorCategory: "Error Category:",
  textFont: "Text / Font",
  audioRecitation: "Audio Recitation",
  otherIssue: "Other Issue",
  description: "Description:",
  describeErrorDetails: "Please describe the error details here...",
  nameOrEmailOptional: "Name or Email (Optional):",
  yourEmailOrContact: "Your email or contact info...",
  cancel: "Cancel",
  submitReport: "Submit Report",
  ayahNotes: "Ayah Notes",
  writeCustomNotes: "Write custom notes, reflections, or tafsir",
  typeNoteHere: "Type your note here...",
  deleteNote: "Delete Note",
  saveNote: "Save Note",
  playWordAudio: "Play Word Audio",
  playRecitation: "Play Ayah Recitation",
  playFullAyah: "Play Full Ayah",
  removeLastReadMark: "Remove Last Read Mark",
  markAsLastRead: "Mark as Last Read",
  removeBookmark: "Remove Bookmark",
  bookmarkAyah: "Bookmark Ayah",
  shareOnWhatsApp: "Share on WhatsApp",
  shareOnTelegram: "Share on Telegram",
  shareOnX: "Share on X",
  shareOnFacebook: "Share on Facebook",
  copyAyah: "Copy Ayah",
  copied: "Copied!",
  word: "Word:",
  surahProgress: "Surah Progress",
  inQuran: "In Quran",
  inSurah: "In Surah",
  times: "times",
  allWords: "All",
  uniqueWords: "Unique",
  groups: "Groups",
  previous: "Previous",
  next: "Next",
  of: "of",
  playAudio: "Play Audio",
  backToSurah: "Back to Reading",

  // Reciter & Qaris
  reciter: "Reciter / Qari",
  selectReciter: "Select Reciter",
  searchReciters: "Search Reciters by name or style...",
  qiratStyle: "Qirat Style",
  defaultReciter: "Sheikh Mishari Rashid al-Afasy (Hafs - Murattal)",
  allReciters: "All Reciters (20)",

  // Audio Sync Section
  audioSyncTitle: "Database Audio Files Synchronization (quran_audio_files)",
  audioSyncSubtitle: "Save complete audio files & word timing segments into D1 Database 'quranalim' (table: quran_audio_files)",
  syncAllSurahsBtn: "Sync All 114 Surahs to DB",
  syncingDbProgress: "Syncing Audio Files to DB...",
  syncCompletedSuccess: "Successfully synced audio files to table 'quran_audio_files' in database 'quranalim'!",
  dbTableStatus: "D1 Table Status: quran_audio_files",
  syncedRecords: "Synced Records in DB:",
  dbBindingName: "D1 Database Binding: DB (quranalim)"
};
