export const apiManager = {
  // Brand & Navigation
  brandTitle: "پبلک API منیجر",
  brandSubtitle: "قرآن کریم کا اوپن سورس اور انتہائی تیز رفتار REST API",
  badgePublicApi: "پبلک API v1.0",
  freeForeverBadge: "100% مفت اور اوپن سورس",
  showSidebar: "سائیڈبار دکھائیں",
  openMenu: "API مینو",
  
  // Navigation Tabs
  overviewTab: "API کا جائزہ",
  explorerTab: "انٹرایکٹو ایکسپلورر",
  codeGenTab: "کوڈ جنریٹر",
  schemaTab: "ڈیٹا بیس سکیما",
  metricsTab: "سسٹم پرفارمنس میٹرکس",
  keysTab: "سینڈ باکس API کیز",
  
  // Overview Section
  welcomeTitle: "عالمی سطح پر قرآنی ایپلیکیشنز کو بااختیار بنانا",
  welcomeDesc: "قرآن عالم اوپن API پلیٹ فارم میں خوش آمدید۔ کلمہ بہ کلمہ قرآنی متون، عثمانی اور انڈو پاک رسم الخط، تراجم، صوتی تلفظ، صفحات اور پاروں کے لے آؤٹ، اور کلاؤڈ ڈیٹا بیس اور ہائی پرفارمنس آبجیکٹ اسٹوریج میں محفوظ آڈیو فائلوں تک براہ راست رسائی حاصل کریں۔",
  quickStartTitle: "کوئیک اسٹارٹ گائیڈ",
  quickStartDesc: "معیاری HTTP fetch درخواستوں کے ذریعے سیکنڈوں میں اپنی پہلی API کال کریں۔ کسی کریڈٹ کارڈ یا ادائیگی کی ضرورت نہیں ہے۔",
  baseUrlTitle: "پروڈکشن بیس URL",
  baseUrlDesc: "تمام API درخواستیں درج ذیل بیس یو آر ایل پر بھیجی جانی چاہئیں:",
  authenticationTitle: "توثیق (Authentication) کی پالیسی",
  authenticationDesc: "تمام پبلک ریڈ اونلی اینڈ پوائنٹس کے لیے کسی توثیق کی ضرورت نہیں ہے۔ ریٹ لمٹ میں اضافے کے لیے اختیاری API کیز 'X-API-Key' ہیڈر میں بھیجی جا سکتی ہیں۔",
  rateLimitTitle: "شرح کی حد اور بینڈوڈتھ",
  rateLimitDesc: "عالمی CDN ایج کیشنگ کے ساتھ فی IP ایڈریس پر پہلے سے طے شدہ ریٹ لمٹ 1000 درخواستیں فی منٹ ہے۔",
  corsTitle: "CORS اور ایج کیشنگ",
  corsDesc: "تمام اینڈ پوائنٹس پر Access-Control-Allow-Origin کو '*' پر سیٹ کیا گیا ہے۔ تیز ترین رسائی کے لیے جوابات دنیا بھر میں موجود ایج لوکیشنز پر محفوظ ہوتے ہیں۔",
  
  // New API Documentation Section
  docSectionTitle: "API کی تکنیکی تفصیلات اور دستاویزات",
  docSectionSubtitle: "تمام پبلک اینڈ پوائنٹس کے لیے بیس URL فارمیٹ، ریٹ لمٹس اور معیاری رسپانس اسٹرکچر کے بارے میں جامع رہنمائی۔",
  docBaseUrlTitle: "بیس یو آر ایل کا ڈھانچہ",
  docBaseUrlDesc: "تمام پبلک API اینڈ پوائنٹس محفوظ HTTPS پروٹوکول کے ذریعے `/api/v1` ورژن کے تحت دستیاب ہیں۔ ورژننگ آپ کی ایپس کے ساتھ مکمل مطابقت کو یقینی بناتی ہے۔",
  docRateLimitTitle: "ریٹ لمٹ کی تفصیلات",
  docRateLimitDesc: "بغیر توثیق کے پبلک ریکوئسٹس 1,000 درخواستیں فی منٹ فی IP تک محدود ہیں۔ ایج کیشے کوٹہ استعمال کیے بغیر بار بار آنے والی درخواستوں کو فوراً پیش کرتا ہے۔ کسٹم کیز کی گنجائش 10,000 ریکوئسٹس فی منٹ ہے۔",
  docResponseFormatTitle: "کامیاب رسپانس کا معیاری فارمیٹ",
  docResponseFormatDesc: "تمام کامیاب درخواستیں 200 OK اسٹیٹس کے ساتھ یونیفائیڈ JSON لفافے میں میٹا ڈیٹا، کل ریکارڈز، عمل درآمد کا وقت اور ڈیٹا اری فراہم کرتی ہیں۔",
  docErrorFormatTitle: "خرابی (Error) کا معیاری فارمیٹ",
  docErrorFormatDesc: "جب درخواست میں غلط پیرامیٹرز ہوں یا ڈیٹا موجود نہ ہو، تو معیاری HTTP اسٹیٹس کوڈز 4xx/5xx کے ساتھ منظم JSON ڈیٹا موصول ہوتا ہے۔",
  
  // Edge API Cache
  cdnCacheTitle: "ایج API کیشنگ (Edge API Caching)",
  cdnCacheDesc: "تیز رفتار ایج کیش API (`caches.default`) کے ذریعے تقویت یافتہ۔ اکثر استعمال ہونے والی کوئریز دنیا بھر کے 300+ ایج مقامات سے 15 ملی سیکنڈ سے بھی کم وقت میں بغیر ڈیٹا بیس پر بوجھ ڈالے فراہم کی جاتی ہیں۔",
  cdnCacheBadge: "ایج کیش فعال ہے",
  cdnCacheTTL: "ایج کیش کا دورانیہ: 24 گھنٹے (`s-maxage=86400`)",

  // Endpoints Info
  availableEndpoints: "بنیادی REST API اینڈ پوائنٹس",
  endpointWordsTitle: "قرآن کے لفظ بہ لفظ کا ڈیٹا",
  endpointWordsDesc: "سورہ، آیت، لفظ کی پوزیشن، صفحہ، یا پارہ نمبر کے لحاظ سے الفاظ کے ریکارڈز حاصل کریں۔",
  endpointSurahTitle: "جامع معلومات برائے سورہ",
  endpointSurahDesc: "تمام 114 سورتوں کے مکمل الفاظ کے سیٹ اور تفصیلی میٹا ڈیٹا کو بازیافت کریں۔",
  endpointSearchTitle: "مکمل قرآنی متنی تلاش",
  endpointSearchDesc: "عربی متن (عثمانی، انڈو پاک، املا)، انگریزی تراجم اور انگریزی صوتی تلفظ میں تلاش کریں۔",
  endpointStatsTitle: "ڈیٹا سیٹ کے اعداد و شمار",
  endpointStatsDesc: "الفاظ کی کل تعداد، آیات، صفحات کی تقسیم اور ڈیٹا بیس کی کارکردگی تک رسائی حاصل کریں۔",
  endpointAudioTitle: "الفاظ کے آڈیو اثاثے",
  endpointAudioDesc: "کلاؤڈ اسٹوریج سے لفظ بہ لفظ MP3 آڈیو فائلوں کے ڈائریکٹ پلے بیک لنکس اور میٹا ڈیٹا۔",
  endpointHealthTitle: "سسٹم ہیلتھ اور اسٹیٹس",
  endpointHealthDesc: "ڈیٹا بیس کے کنکشن اور ایج سرورز کی ریئل ٹائم جانچ کے لیے اینڈ پوائنٹ۔",

  // Explorer & Tester
  testerTitle: "انٹرایکٹو API ٹیسٹنگ سینڈ باکس",
  testerDesc: "اپنے براؤزر سے اینڈ پوائنٹس کی جانچ کریں۔ پیرامیٹرز تبدیل کریں، لائیو درخواستیں بھیجیں اور اسٹیٹس کوڈز، ہیڈرز اور JSON جوابات کا معائنہ کریں۔",
  selectEndpoint: "اینڈ پوائنٹ منتخب کریں",
  queryParams: "کوئری پیرامیٹرز",
  addParam: "پیرامیٹر شامل کریں",
  sendRequest: "درخواست بھیجیں",
  cancellingRequest: "درخواست منسوخ ہو رہی ہے...",
  requestSuccess: "درخواست کامیاب رہی",
  requestFailed: "درخواست ناکام ہو گئی",
  responseStatus: "اسٹیٹس کوڈ",
  responseTime: "رسپانس ٹائم",
  responseSize: "رسپانس سائز",
  responseHeaders: "رسپانس ہیڈرز",
  responseBody: "رسپانس باڈی (JSON)",
  copyResponse: "رسپانس کاپی کریں",
  copiedToast: "کلپ بورڈ پر کاپی ہو گیا!",
  clearHistory: "ہسٹری صاف کریں",
  requestHistory: "حالیہ ٹیسٹنگ ہسٹری",
  paramSurah: "سورہ نمبر (1-114)",
  paramVerse: "آیت نمبر",
  paramSearchQuery: "تلاش کا لفظ",
  paramPage: "مصحف صفحہ (1-604)",
  paramJuz: "پارہ نمبر (1-30)",
  paramLimit: "نتائج کی حد (ڈیفالٹ 50)",
  
  // Code Generator
  codeGenTitle: "کثیر لسانی کوڈ نمونے",
  codeGenDesc: "اپنی پسندیدہ پروگرامنگ زبان یا فریم ورک کے لیے ٹیسٹ شدہ کوڈ اسنیپٹس کو فوری کاپی کریں۔",
  selectLanguage: "زبان / ٹول منتخب کریں",
  copyCode: "کوڈ اسنیپٹ کاپی کریں",
  codeCopiedToast: "کوڈ اسنیپٹ کاپی ہو گیا!",

  // Schema Viewer
  schemaTitle: "قرآنی الفاظ کا ڈیٹا بیس سکیما (`quran_words`)",
  schemaDesc: "`quranalim` ڈیٹا بیس میں شامل تمام 88,246 قرآنی الفاظ کے تفصیلی کالمز کی معلومات۔",
  tableName: "ٹیبل کا نام",
  totalColumns: "کل کالمز",
  totalRecords: "کل ریکارڈز",
  columnName: "کالم کا نام",
  dataType: "ڈیٹا کی قسم",
  descriptionHeader: "تفصیل",
  sampleValue: "نمونہ ویلیو",
  r2BucketTitle: "آڈیو اسٹوریج بکٹ (`bucket`)",
  r2BucketDesc: "لفظ بہ لفظ MP3 آڈیو فائلز (جیسے `wbw/001_001_001.mp3`) جو `quran_words.audio_url` سے منسلک ہیں۔",

  // Metrics
  metricsTitle: "نیٹ ورک میٹرکس اور سسٹم کی صورتحال",
  metricsDesc: "ایج فنکشنز، کلاؤڈ ڈیٹا بیس اور آڈیو اسٹوریج کی لائیو آپریشنل کارکردگی۔",
  serverStatus: "سرور اسٹیٹس",
  operational: "تمام سسٹمز مکمل فعال ہیں",
  avgLatency: "اوسط ایج لیٹنسی",
  totalRequestsToday: "آج کی کل درخواستیں",
  uptimePercent: "اپ ٹائم (30 دن)",
  d1Status: "ریلیشنل ڈیٹا بیس",
  r2Status: "آڈیو اسٹوریج",

  // API Key Playground
  keysTitle: "سینڈ باکس API کی جنریٹر",
  keysDesc: "ہیڈرز کی جانچ اور کلائنٹ انٹیگریشن ٹیسٹ کرنے کے لیے عارضی ڈویلپر کیز بنائیں۔",
  generateKey: "سینڈ باکس کی تیار کریں",
  yourApiKey: "آپ کی فعال سینڈ باکس کی",
  sandboxKeyNotice: "سینڈ باکس کیز ہیڈر ٹیسٹنگ (`X-API-Key: quran_...`) اور ڈویلپر ٹیسٹس کے لیے ہیں۔",
  rateLimitTier: "ریٹ لمٹ کی قسم",
  requestsPerMin: "10,000 درخواستیں فی منٹ",

  // Common UI
  backHome: "ہوم پر واپس جائیں",
  toggleSidebar: "مینو ٹوگل کریں",
  closeMenu: "مینو بند کریں",
  searchPlaceholder: "اینڈ پوائنٹس یا پیرامیٹرز فلٹر کریں...",
  noDataFound: "کوئی ڈیٹا دستیاب نہیں ہے۔",
  loadingData: "API رسپانس لوڈ ہو رہا ہے...",
  cancel: "منسوخ",
  reset: "ری سیٹ",
  refresh: "ڈیٹا ریفریش کریں",
  copy: "کاپی"
};
