export const authorizer = {
  appName: "شناخت اور توثیق کا پورٹل",
  appSubtitle: "مرکزی توثیق، سیکیورٹی سیشنز اور صارف کا انتظام",
  loginTitle: "اپنے اکاؤنٹ میں لاگ ان کریں",
  loginSubtitle: "قرآن عالم کی خدمات تک رسائی کے لیے اپنی تفصیلات درج کریں",
  signupTitle: "نیا اکاؤنٹ بنائیں",
  signupSubtitle: "فوری رسائی کے ساتھ ہماری عالمی کمیونٹی میں شامل ہوں",
  forgotTitle: "پاس ورڈ ری سیٹ کریں",
  forgotSubtitle: "ری سیٹ کوڈ حاصل کرنے کے لیے اپنا رجسٹرڈ ای میل درج کریں",
  resetTitle: "نیا پاس ورڈ درج کریں",
  resetSubtitle: "اپنے اکاؤنٹ کے لیے مضبوط اور محفوظ پاس ورڈ بنائیں",
  sessionsTitle: "فعال سیکیورٹی سیشنز",
  sessionsSubtitle: "اپنے اکاؤنٹ میں لاگ ان شدہ آلات اور IP ایڈریسز کا انتظام کریں",
  profileTitle: "صارف پروفائل اور سیکیورٹی",
  profileSubtitle: "اکاؤنٹ اسٹیٹس، کردار، ای میل تصدیق اور سیکیورٹی ٹوکنز دیکھیں",
  
  // Tabs & Navigation
  tabLogin: "لاگ ان",
  tabSignup: "سائن اپ",
  tabForgot: "پاس ورڈ بھول گئے",
  tabReset: "پاس ورڈ ری سیٹ",
  tabSessions: "فعال سیشنز",
  tabProfile: "میرا اکاؤنٹ",

  // Form Fields
  fullNameLabel: "مکمل نام",
  fullNamePlaceholder: "مثال: عبداللہ محمد",
  emailLabel: "ای میل ایڈریس",
  emailPlaceholder: "name@example.com",
  passwordLabel: "پاس ورڈ",
  passwordPlaceholder: "کم از کم 6 حروف",
  confirmPasswordLabel: "پاس ورڈ کی تصدیق",
  confirmPasswordPlaceholder: "پاس ورڈ دوبارہ درج کریں",
  resetTokenLabel: "ری سیٹ ٹوکن (OTP)",
  resetTokenPlaceholder: "مثال: reset_xxx",
  newPasswordLabel: "نیا پاس ورڈ",
  rememberMe: "مجھے 30 دن کے لیے یاد رکھیں",
  agreeTerms: "میں سروس کی شرائط اور رازداری کی پالیسی سے اتفاق کرتا ہوں",
  quickDemoTip: "فوری ٹیسٹ کی تفصیلات:",

  // Buttons
  signInBtn: "لاگ ان کریں",
  signUpBtn: "اکاؤنٹ بنائیں",
  sendResetBtn: "ری سیٹ لنک بھیجیں",
  savePasswordBtn: "پاس ورڈ اپ ڈیٹ کریں",
  logoutBtn: "لاگ آؤٹ کریں",
  revokeAllSessions: "باقی تمام سیشنز بند کریں",
  backHome: "ہوم پر واپس جائیں",
  forgotPassLink: "پاس ورڈ بھول گئے؟",
  alreadyHaveAccount: "کیا پہلے سے اکاؤنٹ موجود ہے؟",
  noAccountYet: "ابھی تک اکاؤنٹ نہیں ہے؟",
  backToLogin: "لاگ ان پر واپس جائیں",

  // Feedback Messages
  reqFields: "براہ کرم تمام مطلوبہ خانے پُر کریں۔",
  passMismatch: "پاس ورڈز ایک جیسے نہیں ہیں۔",
  passTooShort: "پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔",
  passwordStrength: "پاس ورڈ کی مضبوطی",
  passStrengthWeak: "کمزور",
  passStrengthMedium: "درمیانہ",
  passStrengthStrong: "مضبوط",
  passReqLength: "کم از کم 8 حروف",
  passReqCase: "بڑے اور چھوٹے حروف",
  passReqNumber: "کم از کم 1 ہندسہ",
  passReqSpecial: "کم از کم 1 خاص علامت (@$!%*?&)",
  termsRequired: "آپ کو سروس کی شرائط قبول کرنی ہوں گی۔",
  invalidCreds: "غلط ای میل یا پاس ورڈ۔",
  loginSuccess: "کامیابی سے لاگ ان ہو گئے! دوبارہ خوش آمدید۔",
  signupSuccess: "اکاؤنٹ کامیابی سے بن گیا! اب آپ لاگ ان کر سکتے ہیں۔",
  forgotSuccess: "پاس ورڈ ری سیٹ ٹوکن تیار ہو گیا ہے۔",
  resetSuccess: "پاس ورڈ کامیابی سے ری سیٹ ہو گیا ہے۔",
  logoutSuccess: "کامیابی سے لاگ آؤٹ ہو گئے۔",
  revokeSuccess: "سیشن کامیابی سے ختم کر دیا گیا۔",
  revokeOthersSuccess: "دیگر تمام فعال سیشنز بند کر دیے گئے۔",
  noSessions: "کوئی فعال سیشن نہیں ملا۔",
  notSignedInNote: "آپ اس وقت لاگ ان نہیں ہیں۔ اپنے اکاؤنٹ کی تفصیلات دیکھنے کے لیے براہ کرم لاگ ان یا سائن اپ کریں۔",
  currentSessionBadge: "موجودہ سیشن",
  
  // Database Status Header Card
  d1StatusTitle: "ڈیٹا بیس کنیکٹیویٹی",
  d1StatusConnected: "ڈیٹا بیس انجن فعال ہے",
  d1StatusNotice: "سرور اینڈ پوائنٹس محفوظ صارف توثیقی ٹیبلز سے منسلک ہیں۔",
  
  // Table Labels
  userId: "صارف ID",
  userRole: "کردار",
  userStatus: "اسٹیٹس",
  emailVerified: "ای میل تصدیق شدہ",
  createdDate: "تخلیق کی تاریخ",
  lastLogin: "آخری لاگ ان",
  activeSessionsCount: "فعال سیشنز",
  tokenExpiry: "سیشن کی میعاد",
  ipAddress: "IP ایڈریس",
  deviceAgent: "ڈیوائس / براؤزر",
  action: "ایکشن",
  revokeSession: "منسوخ کریں",
  
  // Search
  searchPlaceholder: "صارفین، سیشنز یا سیٹنگز تلاش کریں...",
  noSearchResults: "کوئی نتیجہ نہیں ملا۔",

  // Branding
  brandName: "قرآن عالم",
  brandTagline: "اسلامک ریسرچ سینٹر",
  brandPortalTagline: "یونیفائیڈ آئیڈینٹی اور ایکسیس مینجمنٹ",

  // Public Auth View Strings
  publicAuthTitle: "توثیقی پورٹل",
  backToApp: "مین ایپ پر واپس جائیں",
  welcomePortal: "شناخت اور توثیق کے پورٹل میں خوش آمدید",
  secureAuthSubtitle: "تیز، محفوظ اور جدید رسائی کا نظام",
  loginPageBadge: "توثیقی نظام",
  signupPageBadge: "نیا صارف اندراج",
  forgotPageBadge: "پاس ورڈ کی بازیابی",
  resetPageBadge: "سیکیورٹی اپ ڈیٹ",
};

export default authorizer;
