export const dashboard = {
  quranKareem: "القرآن الکریم",
  welcomeSub: "خوش آمدید، الٰہی حکمت کے لیے آپ کا پورٹل",
  browseManzil: "منزلیں براؤز کریں",
  browseHizb: "حزب براؤز کریں",
  browseJuz: "پارے براؤز کریں",
  browseSurahs: "سورتیں براؤز کریں",
  verseOfTheDay: "آج کی آیت",
  lastRead: "آخری بار پڑھا گیا",
  resumeReading: "پڑھنا جاری رکھیں",
  recitedFrequently: "اکثر تلاوت کی جانے والی",
  tasbihCounter: "تسبیح کاؤنٹر",
  changeDhikr: "ذکر تبدیل کریں",
  tapToIncrease: "گنتی بڑھانے کے لیے دائرے پر ٹیپ کریں",
};
