export const driveApp = {
  driveTitle: "ڈرائیو",
  subtitle: "کلاؤڈ اسٹوریج اور میڈیا فائلز",
  accessDeniedTitle: "ایڈمنسٹریٹر کی اجازت درکار ہے",
  accessDeniedDesc: "ڈرائیو تک رسائی صرف ایڈمن اکاؤنٹس کے لیے مخصوص ہے۔ براہ کرم ایڈمن اکاؤنٹ سے لاگ ان کریں۔",
  loginRequiredTitle: "لاگ ان درکار ہے",
  loginRequiredDesc: "کلاؤڈ اسٹوریج کے انتظام کے لیے آپ کا ایڈمنسٹریٹر کے طور پر لاگ ان ہونا ضروری ہے۔",
  signInBtn: "لاگ ان صفحہ پر جائیں",
  demoAdminBtn: "بطور ایڈمن لاگ ان کریں (ڈیمو)",
  currentRole: "موجودہ اکاؤنٹ کا کردار",
  userRoleUser: "عام صارف",
  userRoleAdmin: "سسٹم ایڈمن",
  logoutBtn: "لاگ آؤٹ",
  switchAccount: "اکاؤنٹ تبدیل کریں",
  myDrive: "میری ڈرائیو",
  recentFiles: "حالیہ اپ لوڈز",
  starredFiles: "اسٹار شدہ فائلیں",
  trash: "کوڑے دان (Trash)",
  storageAnalytics: "اسٹوریج تجزیات",
  bucketSettings: "ڈرائیو ترتیبات",
  searchPlaceholder: "فائلیں، فولڈرز، ایکسٹینشنز تلاش کریں...",
  uploadFile: "فائلز",
  newFolder: "نیا فولڈر",
  refresh: "ڈرائیو ریفریش کریں",
  viewGrid: "گرڈ ویو",
  viewList: "لسٹ ویو",
  filterAll: "تمام آئٹمز",
  filterImages: "تصاویر",
  filterAudio: "آڈیو فائلز",
  filterDocuments: "دستاویزات",
  filterArchives: "آرکائیو فائلز",
  filterOthers: "دیگر",
  name: "نام",
  size: "سائز",
  type: "قسم",
  modified: "تاریخ ترمیم",
  actions: "اقدامات",
  preview: "پیش منظر",
  download: "ڈاؤن لوڈ",
  shareLink: "لنک شیئر کریں",
  rename: "نام تبدیل کریں",
  delete: "حذف کریں",
  restore: "بحال کریں",
  permanentDelete: "مستقل حذف کریں",
  star: "اسٹار شامل کریں",
  unstar: "اسٹار ہٹائیں",
  details: "تفصیلات",
  totalStorage: "کل اسٹوریج",
  usedStorage: "استعمال شدہ گنجائش",
  freeStorage: "دستیاب گنجائش",
  filesCount: "کل آبجیکٹس",
  foldersCount: "فولڈرز",
  uploadModalTitle: "قرآن عالم ڈرائیو میں فائل اپ لوڈ کریں",
  dropzoneText: "فائلیں یہاں ڈریگ اور ڈراپ کریں، یا منتخب کرنے کے لیے کلک کریں",
  folderModalTitle: "نیا فولڈر بنائیں",
  folderNamePlaceholder: "فولڈر کا نام (مثلاً: آڈیو، کتب، بیک اپ)...",
  createBtn: "فولڈر بنائیں",
  cancelBtn: "منسوخ",
  noFilesFound: "اس فولڈر میں کوئی فائل نہیں ملی۔",
  emptyTrash: "کوڑے دان اس وقت خالی ہے۔",
  publicUrl: "پبلک اسٹوریج لنک",
  copiedToast: "اسٹوریج لنک کاپی ہو گیا!",
  deleteConfirm: "کیا آپ اس آئٹم کو کوڑے دان میں منتقل کرنا چاہتے ہیں؟",
  permanentDeleteConfirm: "کیا آپ واقعی اس فائل کو مستقل طور پر حذف کرنا چاہتے ہیں؟ یہ عمل واپس نہیں ہو سکتا۔",
  adminBadge: "تصدیق شدہ ایڈمن",
  storageOverview: "اسٹوریج کا جائزہ",
  fileTypeDistribution: "فائل کی اقسام کی تقسیم",
  bucketName: "قرآن عالم",
  statusActive: "مربوط اور فعال",
  sidebarLockedTitle: "سائیڈبار مقفل ہے",
  sidebarLockedDesc: "کلاؤڈ اسٹوریج اور اپ لوڈنگ کے فیچرز محفوظ ہیں۔ لاک کھولنے کے لیے لاگ ان کریں۔",
  checkingAuth: "توثیق کی جانچ کی جا رہی ہے...",
  redirecting: "ری ڈائریکٹ ہو رہا ہے...",
  loginRedirectNotice: "ڈرائیو تک رسائی کے لیے لاگ ان درکار ہے۔ لاگ ان صفحہ پر بھیجا جا رہا ہے...",
  adminRedirectNotice: "ڈرائیو تک رسائی کے لیے ایڈمنسٹریٹر کا حق درکار ہے۔ ہوم پیج پر بھیجا جا رہا ہے...",
  copyUrl: "لنک کاپی کریں",
  close: "بند کریں",
  save: "محفوظ کریں",
  itemCount: "آئٹمز",
  backToHome: "ہوم پر واپس جائیں",
  storageStats: "اسٹوریج کے اعداد و شمار",
  allFolders: "فولڈرز اور ڈائرکٹریز",
  allFiles: "تمام فائلیں",
  fileExplorerTitle: "فائل ایکسپلورر",
  folderTreeTitle: "فائل ایکسپلورر",
  downloadManager: "ڈاؤن لوڈ منیجر",
  noFoldersFound: "ابھی تک کوئی فولڈر نہیں بنایا گیا",
  uploadProgress: "اپ لوڈ ہو رہا ہے...",
  uploadManager: "اپ لوڈ منیجر",
  addUrls: "یو آر ایلز (URLs)",
  pasteUrlsLabel: "فائل لنکس درج کریں (ہر لائن میں ایک لنک):",
  pasteUrlsPlaceholder: "https://example.com/file1.pdf\nhttps://example.com/image2.jpg\nhttps://example.com/archive3.zip",
  saveAndUpload: "محفوظ کریں اور اپ لوڈ شروع کریں",
  cancel: "منسوخ",
  invalidUrlsNotice: "براہ کرم کم از کم ایک درست URL درج کریں۔",
  urlsAddedToQueue: "لنکس کی فہرست قطار میں شامل ہو گئی",
  multipleUploads: "ملٹی پل اپ لوڈ منیجر",
  quickTools: "فوری ٹولز",
  driveSettings: "ڈرائیو ترتیبات",
  defaultLayout: "پہلے سے طے شدہ لے آؤٹ",
  autoTrashCleanup: "کوڑے دان کی خودکار صفائی (30 دن)",
  offlineSync: "فائلوں کا آف لائن کیشے",
  storageAlerts: "کم گنجائش کے الرٹس",
  downloadPreference: "ڈاؤن لوڈ کوالٹی موڈ",
  uploadNotifications: "اپ لوڈ اطلاعات",
  settingsSaved: "ترتیبات محفوظ ہو گئیں",
  uploadSuccess: "فائل کامیابی سے اپ لوڈ ہو گئی!",
  fileSizeError: "فائل کا سائز زیادہ سے زیادہ حد سے تجاوز کر گیا ہے۔",
  folderCreatedSuccess: "فولڈر کامیابی سے بن گیا!",
  itemDeletedSuccess: "آئٹم کوڑے دان میں منتقل کر دیا گیا۔",
  itemRestoredSuccess: "آئٹم کامیابی سے بحال ہو گیا۔",
  itemPermanentDeletedSuccess: "آئٹم مستقل طور پر حذف ہو گیا۔",
  activityLogs: "سرگرمی لاگز",
  logTitle: "ڈرائیو سرگرمی لاگز",
  logSubtitle: "سسٹم اور اسٹوریج آڈٹ ٹریل",
  logFilterAll: "تمام ایونٹس",
  logFilterFile: "فائل ایکشنز",
  logFilterSystem: "سیکیورٹی اور سسٹم",
  clearLogs: "لاگ صاف کریں",
  noLogsFound: "ابھی تک کوئی سرگرمی ریکارڈ نہیں ہوئی۔",
  logActionUpload: "فائل اپ لوڈ کی گئی",
  logActionFolder: "فولڈر بنایا گیا",
  logActionDelete: "کوڑے دان میں بھیجا گیا",
  logActionRestore: "آئٹم بحال کیا گیا",
  logActionStar: "اسٹار لگایا گیا",
  logActionSystem: "سیکیورٹی آڈٹ",
  logActionAuth: "ایڈمن سیشن",
  logsClearedToast: "سرگرمی کے لاگز کامیابی سے صاف ہو گئے",
  previousPage: "پچھلا",
  nextPage: "اگلا",
  pageIndicator: "صفحہ {current} از {total}",
  itemsPerPage: "آئٹمز فی صفحہ",
  showingRange: "کل {total} میں سے {start} تا {end} دکھائے جا رہے ہیں",
  firstPage: "پہلا صفحہ",
  lastPage: "آخری صفحہ",
  fileInfo: "فائل کی تفصیلات",
  noFileSelected: "کوئی فائل منتخب نہیں ہے",
  noFileSelectedDesc: "خصوصیات اور میٹا ڈیٹا دیکھنے کے لیے اسٹوریج میں کسی فائل یا فولڈر پر کلک کریں۔",
  path: "ڈائرکٹری پاتھ",
  dropToUploadTitle: "اپ لوڈ کرنے کے لیے فائلیں یا فولڈرز یہاں ڈراپ کریں",
  dropToUploadDesc: "فائلیں خودکار طور پر اس مقام پر اپ لوڈ ہوں گی:",
  dropzoneActive: "اپ لوڈ شروع کرنے کے لیے ماؤس چھوڑیں",
  selectFiles: "فائلز",
  selectFolder: "فولڈر منتخب کریں",
  uploadFolder: "فولڈر",
  dropFilesOrFolder: "فائلیں یا فولڈرز یہاں گھسیٹیں، یا نیچے دیے گئے آپشنز استعمال کریں",
  uploadQueueProgress: "اپ لوڈ قطار اور ریئل ٹائم پیشرفت",
  clearCompleted: "مکمل شدہ صاف کریں",
  startBatchUpload: "قطار کا اپ لوڈ شروع کریں",
  uploadingQueue: "قطار اپ لوڈ ہو رہی ہے...",
  duplicateDetected: "ڈپلیکیٹ فائل کا پتہ چلا",
  alreadyExistsInFolder: "فائل یا فولڈر پہلے ہی اس مقام پر موجود ہے",
  skippedDuplicates: "ڈپلیکیٹ فائلیں یا فولڈرز چھوڑ دیے گئے",
  move: "منتقل کریں",
  moveToFolder: "فولڈر میں منتقل کریں",
  confirmMove: "منتقلی کی تصدیق کریں",
  publicAccess: "پبلک رسائی",
  makePublic: "پبلک بنائیں",
  publicAccessEnabled: "پبلک رسائی فعال ہے",
  publicAccessDisabled: "صرف پرائیویٹ رسائی",
  publicLinkCopied: "پبلک لنک کلپ بورڈ پر کاپی ہو گیا!",
  liveBulkSync: "لائیو بلک سنک (R2 تا D1 ڈیٹا بیس)",
  syncingD1: "R2 کے ریکارڈز کو ڈیٹا بیس میں ہم آہنگ کیا جا رہا ہے...",
  lockFolder: "فولڈر لاک کریں",
  unlockFolder: "فولڈر ان لاک کریں",
  folderLockedNotice: "یہ فولڈر مقفل ہے۔ مواد تک رسائی کے لیے اسے ان لاک کریں۔",
  folderLockedToast: "فولڈر کامیابی سے مقفل ہو گیا!",
  folderUnlockedToast: "فولڈر کامیابی سے ان لاک ہو گیا!",
  locked: "مقفل",
};
