export const quranReadHome = {
  backHome: "ہوم پر واپس جائیں",
  quranReadingHub: "قرآن ریڈنگ ہب",
  resetProgress: "پیش رفت ری سیٹ کریں",
  readingStats: "آپ کی تلاوت کے اعداد و شمار",
  days: "دن",
  completedSurahs: "مکمل شدہ سورتیں",
  surahsFinished: "مکمل شدہ سورتیں %",
  totalVersesRead: "کل پڑھی گئی آیات",
  totalVersesPercent: "کل آیات %",
  overallProgress: "مجموعی قرآن کریم کی پیش رفت",
  recentlyRead: "حال ہی میں پڑھی گئی",
  fullyCompleted: "مکمل طور پر پڑھ لی گئی",
  readingUpToAyah: "آیت نمبر تک پڑھا گیا",
  readyToRead: "پڑھنے کے لیے تیار",
  resetConfirm: "کیا آپ واقعی اپنی تلاوت کی تمام پیش رفت ری سیٹ کرنا چاہتے ہیں؟",
  searchPlaceholder: "نام، ID یا معنی کے ذریعے سورہ تلاش کریں...",
  allSurahs: "تمام سورتیں",
  completed: "مکمل",
  inProgress: "جاری ہے",
  notStarted: "شروع نہیں ہوئی",
  verses: "آیات",
  rukus: "رکوع",
  juz: "پارہ",
  surahIndexTracking: "فہرست سورتیں و ٹریکنگ",
  clearInput: "انپٹ صاف کریں",
  recentSearches: "حالیہ تلاش:",
  removeSearch: "تلاش ہٹائیں",
  clearAllHistory: "تمام ہسٹری صاف کریں",
  clearAll: "تمام صاف کریں",
  markAsIncomplete: "غیر مکمل نشان زد کریں",
  markAsCompleted: "مکمل نشان زد کریں",
  meccan: "مکی",
  medinan: "مدنی",
  noMatchingSurahs: "کوئی ملتی جلتی سورتیں نہیں ملیں۔",
  startReading: "پڑھنا شروع کریں",
  surah: "سورہ",
  ayah: "آیت",
  juzNumber: "پارہ نمبر",
  paraJuz: "پارہ / جزو",
  sajdahProstration: "سجدہ",
  yesSajdah: "ہاں",
  noSajdah: "اس سورہ میں سجدہ نہیں ہے",
  totalWordsEst: "کل الفاظ (تخمینہ)",
  totalLettersEst: "کل حروف (تخمینہ)",
  introduction: "تعارف",
  keyThemes: "بنیادی موضوعات",
  mainLessons: "بنیادی اسباق",
  virtuesBenefits: "فضائل و برکات",
  periodRevelation: "زمانۂ نزول اور تاریخی پس منظر",
  coreSubjects: "بنیادی مضامین اور عقائدی موضوعات",
  practicalLessons: "عملی اسباق اور روزمرہ زندگی کے لیے حکمتیں",
  virtuesSpiritual: "تلاوت کے فضائل اور روحانی برکات",
  reflectionTip: "مشورہ: قرآن کے پیغام پر گہرا تدبر روحانی ہدایت کا ذریعہ ہے۔ تیار ہیں؟ تلاوت پر واپس جائیں۔",
  loadingVerses: "قرآنی آیات لوڈ ہو رہی ہیں...",
  pleaseWait: "براہ کرم ایک لمحہ انتظار کریں",
  failedToLoadSurah: "سورہ کا ڈیٹا لوڈ کرنے میں ناکامی",
  tryAgain: "دوبارہ کوشش کریں",
  loadingNextPage: "اگلا صفحہ لوڈ ہو رہا ہے...",
  backToTop: "اوپر جائیں",
  showSurahSidebar: "سورتوں کی سائیڈ بار دکھائیں",
  searchVersesInSurah: "سورہ میں آیات تلاش کریں",
  audioError: "تلاوت کی آڈیو لوڈ کرنے میں ناکامی۔",
  serverError: "سرور سے رابطہ قائم کرنے میں خرابی۔",

  // Options & Tooltips
  quickOptionsMenu: "فوری اختیارات مینو",
  closeMenu: "مینو بند کریں",
  closeRecitation: "تلاوت بند کریں",
  playSurah: "سورہ چلائیں",
  searchInSurah: "سورہ میں تلاش کریں",
  changeArabicFont: "عربی فونٹس تبدیل کریں",
  toggleBoldFor: "بولڈ ٹیکسٹ آن/آف کریں",
  changeTextSize: "ٹیکسٹ کا سائز تبدیل کریں",
  textSize: "ٹیکسٹ سائز",
  changeLineHeight: "سطر کی اونچائی تبدیل کریں",
  lineHeight: "سطر کی اونچائی",
  changeTextAlignment: "ٹیکسٹ کی الائنمنٹ تبدیل کریں",
  leftAlign: "بائیں الائن",
  centerAlign: "درمیان میں الائن",
  rightAlign: "دائیں الائن",
  justifyAlign: "جسٹفائی الائن",
  tooltipSettings: "ٹول ٹپ ترتیبات",
  tooltipOptions: "ٹول ٹپ اختیارات",
  translation: "ترجمہ",
  transliteration: "تلفظ (ٹرانسلٹریشن)",
  fontSize: "فونٹ سائز",

  // Sidebar & Navigation
  surahList: "سورتوں کی فہرست",
  surahs: "سورتیں",
  bookmarks: "بک مارکس",
  notes: "نوٹس",
  options: "اختیارات",
  shortcuts: "شارٹ کٹس",
  keyboardShortcuts: "کی بورڈ شارٹ کٹس",
  searchShortcutsPlaceholder: "شارٹ کٹس تلاش کریں...",
  shortcutHelpTitle: "مفید کی بورڈ شارٹ کٹس",
  shortcutHelpDesc: "القرآن ریڈر کے لیے تیز ترین نیویگیشن اور کنٹرول کیز۔",
  categoryAudio: "آڈیو اور تلاوت",
  categoryNavigation: "نیویگیشن اور قراءت",
  categoryInterface: "انٹرفیس اور تلاش",
  shortcutPlayPause: "آڈیو پلے / پاز",
  shortcutNextVerse: "اگلی آیت",
  shortcutPrevVerse: "پچھلی آیت",
  shortcutSearch: "سرچ بار کھولیں",
  shortcutToggleSidebar: "سائیڈ بار آن/آف",
  shortcutBookmark: "آیت بک مارک کریں",
  shortcutNextSurah: "اگلی سورہ",
  shortcutPrevSurah: "پچھلی سورہ",
  shortcutCloseModal: "اوورلیز بند کریں",
  shortcutScrollTop: "سب سے اوپر جائیں",
  keySpace: "Space",
  keyArrowRight: "→ دائیں تیر",
  keyArrowLeft: "← بایاں تیر",
  keyArrowUp: "↑ اوپر والا تیر",
  keyArrowDown: "↓ نیچے والا تیر",
  keyEsc: "Esc",
  keyCtrlK: "Ctrl + K",
  keyCtrlB: "Ctrl + B",
  keyShiftN: "Shift + N",
  keyShiftP: "Shift + P",
  noShortcutsFound: "کوئی مطابق شارٹ کٹ نہیں ملا۔",
  recitationAndSearch: "تلاوت اور تلاش",
  textAppearance: "متن کی ظاہری شکل",
  searchSurah: "سورہ تلاش کریں...",
  recent: "حالیہ:",
  clear: "صاف کریں",
  noSurahsFound: "کوئی سورہ نہیں ملی",
  typeMeccanLabel: "مکی",
  typeMedinanLabel: "مدنی",
  versesLabel: "آیات",
  noBookmarks: "ابھی تک کوئی بک مارک محفوظ نہیں ہوا۔",
  ayahNo: "آیت ",
  hideSidebar: "سائیڈ بار چھپائیں",
  showSidebar: "سائیڈ بار دکھائیں",
  closeSidebar: "سائیڈ بار بند کریں",
  loadAllPages: "تمام صفحات لوڈ کریں",

  // Search & Playback Controls
  searchVersesPlaceholder: "اس سورہ میں کوئی بھی لفظ تلاش کریں...",
  resultsFound: "{count} نتیجہ/نتائج ملے",
  noResultsFound: "کوئی نتیجہ نہیں ملا۔ اپنے الفاظ کی ہجائی درست کریں یا دوسرے الفاظ تلاش کریں!",
  autoplayNextSurah: "اگلی سورہ خود بخود چلائیں",
  repeatMode: "تکرار کا موڈ",
  repeatNone: "بند",
  repeatAyah: "آیت",
  repeatSurah: "سورہ",
  repeatAll: "تمام",
  detailsAndInfo: "تفصیلات و معلومات",
  previousAyah: "پچھلی آیت",
  playPause: "چلائیں / روکیں",
  nextAyah: "اگلی آیت",
  stop: "روک دیں",
  mute: "آواز بند کریں",
  unmute: "آواز کھولیں",
  volume: "والیم",
  playbackSpeed: "پلے بیک کی رفتار",
  repeat: "تکرار",
  shuffle: "بے ترتیب (شفل)",
  autoNext: "خودکار اگلا",

  // Confirms & Headers
  deleteBookmarkConfirm: "کیا آپ واقعی تمام بک مارکس ختم کرنا چاہتے ہیں؟",
  deleteNoteConfirm: "کیا آپ واقعی اس نوٹ کو ڈیلیٹ کرنا چاہتے ہیں؟",
  page: "صفحہ",
  previousSurah: "پچھلی سورہ",
  nextSurah: "اگلی سورہ",
  inTheNameOfAllah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",

  // Context Menu, Notes & Error Reports
  editNote: "نوٹ میں ترمیم کریں",
  addNote: "نوٹ شامل کریں",
  foundAnError: "غلطی ملی",
  reportAnError: "غلطی کی رپورٹ کریں",
  reportSubmitted: "رپورٹ جمع کر دی گئی!",
  reportThankYou: "رپورٹ کرنے کا شکریہ۔ ہم جلد ہی اس کا جائزہ لے کر اصلاح کریں گے۔",
  close: "بند کریں",
  targetContext: "متعلقہ سیاق و سباق:",
  errorCategory: "غلطی کی قسم:",
  textFont: "متن / فونٹ",
  audioRecitation: "صوتی تلاوت",
  otherIssue: "دیگر مسئلہ",
  description: "تفصیل:",
  describeErrorDetails: "براہ کرم یہاں غلطی کی تفصیلات لکھیں...",
  nameOrEmailOptional: "نام یا ای میل (اختیاری):",
  yourEmailOrContact: "آپ کا ای میل یا رابطہ نمبر...",
  cancel: "منسوخ کریں",
  submitReport: "رپورٹ جمع کریں",
  ayahNotes: "آیت کے نوٹس",
  writeCustomNotes: "اپنے نوٹس، نکات یا تفسیر لکھیں",
  typeNoteHere: "اپنا نوٹ یہاں لکھیں...",
  deleteNote: "نوٹ ڈیلیٹ کریں",
  saveNote: "نوٹ محفوظ کریں",
  playWordAudio: "لفظ کی آڈیو چلائیں",
  playRecitation: "آیت کی تلاوت چلائیں",
  playFullAyah: "مکمل آیت چلائیں",
  removeLastReadMark: "آخری بار پڑھے گئے کے نشان کو ہٹائیں",
  markAsLastRead: "آخری بار پڑھا گیا کے طور پر نشان زد کریں",
  removeBookmark: "بک مارک ہٹائیں",
  bookmarkAyah: "آیت بک مارک کریں",
  shareOnWhatsApp: "WhatsApp پر شیئر کریں",
  shareOnTelegram: "Telegram پر شیئر کریں",
  shareOnX: "X (ٹوئٹر) پر شیئر کریں",
  shareOnFacebook: "Facebook پر شیئر کریں",
  copyAyah: "آیت کاپی کریں",
  copied: "کاپی ہو گیا!",
  word: "لفظ:",
  surahProgress: "سورہ کی پیش رفت"
};
