export const quranReadHome = {
  backHome: "ہوم پر واپس جائیں",
  quranReadingHub: "قرآن ریڈنگ سینٹر",
  brandSubtitle: "ڈیجیٹل قرآن کریم اور تلاوت کا ساتھی",
  digitalQuranReading: "ڈیجیٹل قرآن ریڈنگ اور ٹریکنگ سسٹم",
  toggleSidebar: "سائیڈبار ٹوگل کریں",
  selectLanguage: "زبان منتخب کریں",
  resetProgress: "پیشرفت ری سیٹ کریں",
  readingStats: "آپ کے مطالعہ کے اعداد و شمار",
  days: "دن",
  completedSurahs: "مکمل شدہ سورتیں",
  surahsFinished: "مکمل شدہ سورتوں کا %",
  totalVersesRead: "کل تلاوت شدہ آیات",
  totalVersesPercent: "کل تلاوت شدہ آیات کا %",
  overallProgress: "قرآن مجید میں مجموعی پیشرفت",
  recentlyRead: "حال ہی میں پڑھی گئیں",
  fullyCompleted: "مکمل پڑھ لی گئی",
  readingUpToAyah: "تلاوت آیت تک پہنچی",
  readyToRead: "تلاوت کے لیے تیار",
  resetConfirm: "کیا آپ واقعی اپنی تمام تلاوت کی پیشرفت ری سیٹ کرنا چاہتے ہیں؟",
  searchPlaceholder: "نام، نمبر یا معنی کے ذریعے سورہ تلاش کریں...",
  allSurahs: "تمام سورتیں",
  completed: "مکمل شدہ",
  inProgress: "جاری ہے",
  notStarted: "شروع نہیں ہوئی",
  verses: "آیات",
  rukus: "رکوعات",
  juz: "پارے",
  surahIndexTracking: "فہرست سورتیں اور ٹریکنگ",

  // Daily Ayah & Banner
  dailyAyahTitle: "آج کی آیت مبارکہ (آیۃ الکرسی)",
  dailyAyahArabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
  dailyAyahTranslation: "اللہ وہ ہے جس کے سوا کوئی معبود نہیں، ہمیشہ زندہ رہنے والا، تمام کائنات کو سنبھالنے والا، نہ اسے اونگھ آتی ہے نہ نیند، جو کچھ آسمانوں میں ہے اور جو کچھ زمین میں ہے سب اسی کا ہے۔",
  readSurahContext: "سورۃ البقرہ کی تلاوت",

  // Quick Modes
  quickModesTitle: "قرآن خوانی کی خصوصیات اور فوری طریقے",
  mushafMode: "مصحف ریڈر موڈ",
  mushafModeDesc: "کلاسیکی 15 سطری مصحف فارمیٹ میں صفحہ بہ صفحہ قرآن کریم کی تلاوت۔",
  audioReciter: "صوتی تلاوت",
  audioReciterDesc: "آیات کی ہم وقتی ہائی لائٹنگ کے ساتھ نامور قراء کی تلاوت سنیں۔",
  bookmarksNotes: "بک مارکس اور نوٹس",
  bookmarksNotesDesc: "اپنی محفوظ شدہ آیات، تدبر اور ذاتی نوٹس تک فوری رسائی۔",
  juzIndex: "30 پاروں کی فہرست",
  juzIndexDesc: "ایک کلک میں قرآن مجید کے کسی بھی پارے پر براہ راست جائیں۔",
  statsAnalytics: "تلاوت کے تجزیات",
  statsAnalyticsDesc: "روزانہ کا تسلسل، تلاوت شدہ آیات اور تکمیل کی شرح ٹریک کریں۔",
  recommendedSurahs: "تجویز کردہ سورتیں",
  recommendedSurahsDesc: "سورۃ یٰسین، الملک، الکہف، اور الرحمٰن تک فوری رسائی۔",

  // Juz Quick Grid
  juzGridTitle: "قرآن مجید کے 30 پاروں کا فوری نیویگیشن گرڈ",
  juzPara: "پارہ",
  startsAtSurah: "شروع سورۃ",

  // Virtues & Merits
  virtuesTitle: "تلاوتِ قرآن مجید کے فضائل اور برکات",
  virtue1Title: "ہر حرف پر دس نیکیاں",
  virtue1Desc: "نبی کریم ﷺ نے فرمایا: جس نے کتاب اللہ کا ایک حرف پڑھا اس کے لیے ایک نیکی ہے اور ایک نیکی دس گنا کے برابر ہے۔",
  virtue2Title: "روحانی سکون اور ہدایت",
  virtue2Desc: "قرآن کریم دلوں کو تسکین بخشتا ہے اور روزمرہ زندگی کو الٰہی حکمت سے منور کرتا ہے۔",
  virtue3Title: "قیامت کے دن شفاعت",
  virtue3Desc: "قرآن مجید قیامت کے دن اپنے پڑھنے والوں اور اس پر عمل کرنے والوں کی شفاعت کرے گا۔",
  clearInput: "صاف کریں",
  recentSearches: "حالیہ تلاش:",
  removeSearch: "تلاش حذف کریں",
  clearAllHistory: "تمام ہسٹری صاف کریں",
  clearAll: "سب صاف کریں",
  markAsIncomplete: "نامکمل قرار دیں",
  markAsCompleted: "مکمل قرار دیں",
  meccan: "مکی",
  medinan: "مدنی",
  noMatchingSurahs: "کوئی مماثل سورہ نہیں ملی۔",
  startReading: "تلاوت شروع کریں",
  surah: "سورہ",
  ayah: "آیت",
  juzNumber: "پارہ نمبر",
  paraJuz: "پارہ",
  sajdahProstration: "سجدہ تلاوت",
  yesSajdah: "ہے",
  noSajdah: "اس سورہ میں سجدہ نہیں ہے",
  totalWordsEst: "کل الفاظ (تخمینی)",
  totalLettersEst: "کل حروف (تخمینی)",
  introduction: "تعارف",
  keyThemes: "اہم موضوعات",
  mainLessons: "بنیادی اسباق",
  virtuesBenefits: "فضائل و برکات",
  periodRevelation: "نزول کا دور اور پس منظر",
  coreSubjects: "بنیادی عقائد و مضامین",
  practicalLessons: "روزمرہ زندگی کے لیے عملی اسباق",
  virtuesSpiritual: "تلاوت کی روحانی برکات اور ثواب",
  reflectionTip: "نصیحت: قرآنی آیات میں تدبر و غور و فکر قلبی ہدایت کا ذریعہ ہے۔ کیا آپ تیار ہیں؟ تلاوت پر واپس جائیں۔",
  loadingVerses: "قرآنی آیات لوڈ ہو رہی ہیں...",
  pleaseWait: "براہ کرم تھوڑی دیر انتظار کریں",
  failedToLoadSurah: "سورہ کا ڈیٹا لوڈ کرنے میں ناکامی ہوئی",
  tryAgain: "دوبارہ کوشش کریں",
  loadingNextPage: "اگلا صفحہ لوڈ ہو رہا ہے...",
  backToTop: "صفحے کے شروع میں جائیں",
  showSurahSidebar: "سورتوں کا سائیڈبار دکھائیں",
  searchVersesInSurah: "اس سورہ میں آیات تلاش کریں",
  audioError: "تلاوت کی آڈیو لوڈ کرنے میں خرابی پیش آئی۔",
  serverError: "سرور سے رابطہ قائم نہیں ہو سکا۔",

  // Options & Tooltips
  quickOptionsMenu: "فوری اختیارات کا مینو",
  closeMenu: "مینو بند کریں",
  closeRecitation: "تلاوت بند کریں",
  playSurah: "سورہ سنیں",
  searchInSurah: "سورہ میں تلاش کریں",
  changeArabicFont: "عربی فونٹ تبدیل کریں",
  toggleBoldFor: "بولڈ فونٹ آن/آف",
  changeTextSize: "ٹیکسٹ سائز تبدیل کریں",
  textSize: "ٹیکسٹ سائز",
  changeLineHeight: "لائنوں کا فاصلہ تبدیل کریں",
  lineHeight: "لائنوں کا فاصلہ",
  changeTextAlignment: "متن کی سیدھ تبدیل کریں",
  leftAlign: "بائیں سیدھ",
  centerAlign: "درمیانی سیدھ",
  rightAlign: "دائیں سیدھ",
  justifyAlign: "دونوں طرف برابر",
  tooltipSettings: "ٹول ٹپ ترتیبات",
  tooltipOptions: "ٹول ٹپ کے اختیارات",
  translation: "ترجمہ",
  chineseTranslation: "چینی ترجمہ",
  chineseSimplified: "آسان چینی (简体中文)",
  chineseTraditional: "روایتی چینی (繁體中文)",
  chinesePinyin: "پنین (Pinyin)",
  chineseZhuyin: "ژوین (Zhuyin)",
  transliteration: "رومن انگریزی تلفظ",
  transliterationStyle: "تلفظ کا انداز",
  transliterationNormal: "عام",
  transliterationSyllables: "الفاظ کے ٹکڑے",
  transliterationSimpleTajweed: "سادہ تجوید",
  transliterationAdvancedTajweed: "ایڈوانسڈ تجوید",
  fontSize: "فونٹ سائز",

  // Sidebar & Navigation
  surahList: "سورتوں کی فہرست",
  juzList: "پاروں کی فہرست",
  hizbList: "احزاب کی فہرست",
  manzilList: "منازل کی فہرست",
  sajdahList: "سجدوں کی فہرست",
  rukuList: "رکوعات کی فہرست",
  pageList: "صفحات کی فہرست",
  mushafOrder: "مصحف کی ترتیب",
  revelationOrder: "ترتیبِ نزول",
  revelationNo: "نزول نمبر",
  surahNo: "سورہ",
  hizb: "حزب",
  manzil: "منزل",
  sajdah: "سجدہ",
  surahs: "سورتیں",
  bookmarks: "بک مارکس",
  notes: "نوٹس",
  options: "اختیارات",
  shortcuts: "شارٹ کٹس",
  keyboardShortcuts: "کی بورڈ شارٹ کٹس",
  searchShortcutsPlaceholder: "شارٹ کٹس تلاش کریں...",
  shortcutHelpTitle: "مفید کی بورڈ شارٹ کٹس",
  shortcutHelpDesc: "قرآن ریڈر کو تیزی سے چلانے اور کنٹرول کرنے کے لیے شارٹ کٹس۔",
  categoryAudio: "آڈیو اور تلاوت",
  categoryNavigation: "نیویگیشن اور مطالعہ",
  categoryInterface: "انٹرفیس اور تلاش",
  shortcutPlayPause: "تلاوت چلائیں / روکیں",
  shortcutNextVerse: "اگلی آیت",
  shortcutPrevVerse: "پچھلی آیت",
  shortcutSearch: "تلاش کھولیں",
  shortcutToggleSidebar: "سائیڈبار کھولیں / بند کریں",
  shortcutBookmark: "آیت پر بک مارک لگائیں",
  shortcutNextSurah: "اگلی سورہ",
  shortcutPrevSurah: "پچھلی سورہ",
  shortcutCloseModal: "ونڈو بند کریں",
  shortcutScrollTop: "صفحے کے اوپر جائیں",
  keySpace: "Space",
  keyArrowRight: "→ دایاں تیر",
  keyArrowLeft: "← بایاں تیر",
  keyArrowUp: "↑ اوپر کا تیر",
  keyArrowDown: "↓ نیچے کا تیر",
  keyEsc: "Esc",
  keyCtrlK: "Ctrl + K",
  keyCtrlB: "Ctrl + B",
  keyShiftN: "Shift + N",
  keyShiftP: "Shift + P",
  noShortcutsFound: "کوئی مماثل شارٹ کٹ نہیں ملا۔",
  recitationAndSearch: "تلاوت اور تلاش",
  textAppearance: "متن کی ظاہری شکل",
  searchSurah: "سورہ تلاش کریں...",
  searchJuz: "پارہ تلاش کریں...",
  searchHizb: "حزب تلاش کریں...",
  searchManzil: "منزل تلاش کریں...",
  searchSajdah: "سجدہ تلاش کریں...",
  recent: "حالیہ:",
  clear: "صاف کریں",
  noSurahsFound: "کوئی سورہ نہیں ملی",
  noJuzFound: "کوئی پارہ نہیں ملا",
  noHizbFound: "کوئی حزب نہیں ملا",
  noManzilFound: "کوئی منزل نہیں ملی",
  noSajdahFound: "کوئی سجدہ نہیں ملا",
  typeMeccanLabel: "مکی",
  typeMedinanLabel: "مدنی",
  versesLabel: "آیات",
  noBookmarks: "ابھی تک کوئی بک مارک محفوظ نہیں کیا گیا۔",
  ayahNo: "آیت ",
  hideSidebar: "سائیڈبار چھپائیں",
  showSidebar: "سائیڈبار دکھائیں",
  closeSidebar: "سائیڈبار بند کریں",
  loadAllPages: "تمام صفحات لوڈ کریں",

  // Search & Playback Controls
  searchVersesPlaceholder: "اس سورہ میں کوئی لفظ تلاش کریں...",
  resultsFound: "{count} نتائج ملے",
  noResultsFound: "کوئی نتیجہ نہیں ملا۔ املا چیک کریں یا مختلف الفاظ آزمائیں!",
  autoplayNextSurah: "اگلی سورہ خودکار چلائیں",
  repeatMode: "تکرار کا موڈ",
  repeatNone: "بند",
  repeatAyah: "آیت",
  repeatSurah: "سورہ",
  repeatAll: "تمام",
  detailsAndInfo: "تفصیلات اور معلومات",
  surahInfo: "سورہ کی معلومات",
  previousAyah: "پچھلی آیت",
  playPause: "چلائیں / روکیں",
  nextAyah: "اگلی آیت",
  stop: "روک دیں",
  mute: "آواز بند کریں",
  unmute: "آواز کھولیں",
  volume: "والیوم",
  playbackSpeed: "سپیڈ",
  repeat: "تکرار",
  shuffle: "بے ترتیب",
  autoNext: "خودکار اگلا",

  // Confirms & Headers
  deleteBookmarkConfirm: "کیا آپ واقعی تمام بک مارکس حذف کرنا چاہتے ہیں؟",
  deleteNoteConfirm: "کیا آپ واقعی اس نوٹ کو حذف کرنا چاہتے ہیں؟",
  page: "صفحہ",
  previousSurah: "پچھلی سورہ",
  nextSurah: "اگلی سورہ",
  inTheNameOfAllah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",

  // Context Menu, Notes & Error Reports
  editNote: "نوٹ میں ترمیم کریں",
  addNote: "نوٹ شامل کریں",
  foundAnError: "غلطی کی نشاندہی",
  reportAnError: "غلطی کی رپورٹ بھیجیں",
  reportSubmitted: "رپورٹ جمع ہو گئی!",
  reportThankYou: "مطلع کرنے کا شکریہ۔ ہم اس کا جائزہ لے کر جلد تصحیح کریں گے۔",
  close: "بند کریں",
  targetContext: "مقام:",
  errorCategory: "غلطی کی قسم:",
  textFont: "متن / فونٹ",
  audioRecitation: "صوتی تلاوت",
  otherIssue: "دیگر مسئلہ",
  description: "تفصیل:",
  describeErrorDetails: "براہ کرم غلطی کی تفصیلات یہاں لکھیں...",
  nameOrEmailOptional: "نام یا ای میل (اختیاری):",
  yourEmailOrContact: "آپ کا ای میل یا رابطہ...",
  cancel: "منسوخ",
  submitReport: "رپورٹ بھیجیں",
  ayahNotes: "آیت کے نوٹس",
  writeCustomNotes: "اپنے ذاتی نوٹس اور تدبر لکھیں",
  typeNoteHere: "اپنا نوٹ یہاں درج کریں...",
  deleteNote: "نوٹ حذف کریں",
  saveNote: "نوٹ محفوظ کریں",
  playWordAudio: "لفظ کی آڈیو سنیں",
  playRecitation: "آیت کی تلاوت سنیں",
  playFullAyah: "مکمل آیت سنیں",
  removeLastReadMark: "آخری تلاوت کا نشان ہٹائیں",
  markAsLastRead: "آخری تلاوت کا نشان لگائیں",
  removeBookmark: "بک مارک ہٹائیں",
  bookmarkAyah: "آیت پر بک مارک لگائیں",
  shareOnWhatsApp: "واٹس ایپ پر شیئر کریں",
  shareOnTelegram: "ٹیلیگرام پر شیئر کریں",
  shareOnX: "ایکس (ٹوئٹر) پر شیئر کریں",
  shareOnFacebook: "فیس بک پر شیئر کریں",
  copyAyah: "آیت کاپی کریں",
  copied: "کاپی ہو گیا!",
  word: "لفظ:",
  surahProgress: "سورہ کی پیشرفت",
  inQuran: "قرآن میں",
  inSurah: "اس سورہ میں",
  times: "مرتبہ",
  allWords: "تمام",
  uniqueWords: "منفرد",
  groups: "گروپس",
  previous: "پچھلا",
  next: "اگلا",
  of: "از",
  playAudio: "آڈیو چلائیں",
  backToSurah: "تلاوت پر واپس جائیں",

  // Reciter & Qaris
  reciter: "قاری",
  selectReciter: "قاری منتخب کریں",
  searchReciters: "نام یا قراءت کے انداز سے تلاش کریں...",
  qiratStyle: "قراءت کا انداز",
  defaultReciter: "شیخ مشاری راشد العفاسی (حفص - مرتل)",
  allReciters: "تمام قراء (20)",

  // Audio Sync Section
  audioSyncTitle: "ڈیٹا بیس کے ساتھ آڈیو فائلز کی سنکرونائزیشن (quran_audio_files)",
  audioSyncSubtitle: "مکمل آڈیو فائلز اور الفاظ کے ٹائمنگز کو D1 ڈیٹا بیس 'quranalim' (ٹیبل: quran_audio_files) میں محفوظ کریں",
  syncAllSurahsBtn: "تمام 114 سورتوں کو ڈیٹا بیس کے ساتھ سنک کریں",
  syncingDbProgress: "آڈیو فائلز کو ڈیٹا بیس میں سنک کیا جا رہا ہے...",
  syncCompletedSuccess: "آڈیو فائلز کامیابی کے ساتھ ڈیٹا بیس 'quranalim' کے 'quran_audio_files' ٹیبل میں ہم آہنگ ہو گئی ہیں!",
  dbTableStatus: "D1 ٹیبل اسٹیٹس: quran_audio_files",
  syncedRecords: "ڈیٹا بیس میں سنک شدہ ریکارڈز:",
  dbBindingName: "D1 ڈیٹا بیس بائنڈنگ: DB (quranalim)"
};
