export const quranReadHome = {
  backHome: "بازگشت به خانه",
  quranReadingHub: "مرکز قرائت قرآن",
  resetProgress: "بازنشانی پیشرفت",
  readingStats: "آمار قرائت شما",
  days: "روز",
  completedSurahs: "سوره‌های تکمیل شده",
  surahsFinished: "درصد سوره‌های تمام شده %",
  totalVersesRead: "کل آیات خوانده شده",
  totalVersesPercent: "درصد کل آیات %",
  overallProgress: "پیشرفت کلی قرآن کریم",
  recentlyRead: "اخیر خوانده شده",
  fullyCompleted: "کاملاً تکمیل شده",
  readingUpToAyah: "خواندن تا آیه",
  readyToRead: "آماده برای خواندن",
  resetConfirm: "آیا مطمئن هستید که می‌خواهید تمام پیشرفت قرائت خود را بازنشانی کنید؟",
  searchPlaceholder: "جستجوی سوره بر اساس نام، شناسه یا معنی...",
  allSurahs: "همه سوره‌ها",
  completed: "تکمیل شده",
  inProgress: "در حال خواندن",
  notStarted: "شروع نشده",
  verses: "آیات",
  rukus: "رکوع‌ها",
  juz: "جزء",
  surahIndexTracking: "فهرست و پیگیری سوره‌ها",
  clearInput: "پاک‌سازی ورودی",
  recentSearches: "جستجوهای اخیر:",
  removeSearch: "حذف جستجو",
  clearAllHistory: "پاک‌سازی تمام تاریخچه",
  clearAll: "پاک‌سازی همه",
  markAsIncomplete: "علامت‌گذاری به عنوان ناتمام",
  markAsCompleted: "علامت‌گذاری به عنوان تکمیل شده",
  meccan: "مکی",
  medinan: "مدنی",
  noMatchingSurahs: "هیچ سوره مطابقی یافت نشد.",
  startReading: "شروع خواندن",
  surah: "سوره",
  ayah: "آیه",
  juzNumber: "شماره جزء",
  paraJuz: "پاره / جزء",
  sajdahProstration: "سجده تلاوت",
  yesSajdah: "بله",
  noSajdah: "سجده‌ای در این سوره وجود ندارد",
  totalWordsEst: "کل کلمات (تخمینی)",
  totalLettersEst: "کل حروف (تخمینی)",
  introduction: "مقدمه",
  keyThemes: "موضوعات کلیدی",
  mainLessons: "درس‌های اصلی",
  virtuesBenefits: "فضائل و برکات",
  periodRevelation: "زمان نزول و زمینه تاریخی",
  coreSubjects: "محورهای اصلی و موضوعات عقیدتی",
  practicalLessons: "درس‌های عملی و حکمت‌ها برای زندگی روزمره",
  virtuesSpiritual: "فضائل و برکات معنوی تلاوت",
  reflectionTip: "نکته: تفکر عمیق در پیام قرآن منبع هدایت معنوی است. آماده‌اید؟ به تلاوت بازگردید.",
  loadingVerses: "در حال بارگذاری آیات قرآنی...",
  pleaseWait: "لطفاً چند لحظه صبر کنید",
  failedToLoadSurah: "خطا در بارگذاری اطلاعات سوره",
  tryAgain: "تلاش مجدد",
  loadingNextPage: "در حال بارگذاری صفحه بعدی...",
  backToTop: "بازگشت به بالا",
  showSurahSidebar: "نمایش نوار کناری سوره‌ها",
  searchVersesInSurah: "جستجوی آیات در سوره",
  audioError: "خطا در بارگذاری صوت تلاوت.",
  serverError: "خطا در اتصال به سرور.",

  // Options & Tooltips
  quickOptionsMenu: "منوی گزینه‌های سریع",
  closeMenu: "بستن منو",
  closeRecitation: "بستن تلاوت",
  playSurah: "پخش سوره",
  searchInSurah: "جستجو در سوره",
  changeArabicFont: "تغییر فونت عربی",
  toggleBoldFor: "تغییر حالت ضخیم (Bold)",
  changeTextSize: "تغییر اندازه متن",
  textSize: "اندازه متن",
  changeLineHeight: "تغییر فاصله خطوط",
  lineHeight: "فاصله خطوط",
  changeTextAlignment: "تغییر چیدمان متن",
  leftAlign: "چپ‌چین",
  centerAlign: "وسط‌چین",
  rightAlign: "راست‌چین",
  justifyAlign: "هم‌تراز (Justify)",
  tooltipSettings: "تنظیمات راهنما",
  tooltipOptions: "گزینه‌های راهنما",
  translation: "ترجمه",
  transliteration: "آوانویسی (ترانسلیتریشن)",
  fontSize: "اندازه قلم",

  // Sidebar & Navigation
  surahList: "فهرست سوره‌ها",
  surahs: "سوره‌ها",
  bookmarks: "نشانک‌ها",
  notes: "یادداشت‌ها",
  options: "گزینه‌ها",
  shortcuts: "میانبرها",
  keyboardShortcuts: "میانبرهای صفحه کلید",
  searchShortcutsPlaceholder: "جستجوی میانبرها...",
  shortcutHelpTitle: "میانبرهای کاربردی صفحه کلید",
  shortcutHelpDesc: "کلیدهای سریع برای پیمایش و کنترل قرآن‌خوان.",
  categoryAudio: "صوت و تلاوت",
  categoryNavigation: "پیمایش و خواندن",
  categoryInterface: "رابط کاربری و جستجو",
  shortcutPlayPause: "پخش / توقف صوت",
  shortcutNextVerse: "آیه بعدی",
  shortcutPrevVerse: "آیه قبلی",
  shortcutSearch: "باز کردن نوار جستجو",
  shortcutToggleSidebar: "تغییر وضعیت نوار کناری",
  shortcutBookmark: "نشانک‌گذاری آیه",
  shortcutNextSurah: "سوره بعدی",
  shortcutPrevSurah: "سوره قبلی",
  shortcutCloseModal: "بستن پنجره‌های شناور",
  shortcutScrollTop: "پیمایش به بالا",
  keySpace: "Space",
  keyArrowRight: "→ کلید راست",
  keyArrowLeft: "← کلید چپ",
  keyArrowUp: "↑ کلید بالا",
  keyArrowDown: "↓ کلید پایین",
  keyEsc: "Esc",
  keyCtrlK: "Ctrl + K",
  keyCtrlB: "Ctrl + B",
  keyShiftN: "Shift + N",
  keyShiftP: "Shift + P",
  noShortcutsFound: "هیچ میانبر مطابقی یافت نشد.",
  recitationAndSearch: "تلاوت و جستجو",
  textAppearance: "ظاهر متن",
  searchSurah: "جستجوی سوره...",
  recent: "اخیر:",
  clear: "پاک‌سازی",
  noSurahsFound: "سوره‌ای یافت نشد",
  typeMeccanLabel: "مکی",
  typeMedinanLabel: "مدنی",
  versesLabel: "آیات",
  noBookmarks: "هنوز هیچ نشانکی ذخیره نشده است.",
  ayahNo: "آیه ",
  hideSidebar: "پنهان کردن نوار کناری",
  showSidebar: "نمایش نوار کناری",
  closeSidebar: "بستن نوار کناری",
  loadAllPages: "بارگذاری همه صفحات",

  // Search & Playback Controls
  searchVersesPlaceholder: "هر کلمه‌ای را در این سوره جستجو کنید...",
  resultsFound: "{count} نتیجه یافت شد",
  noResultsFound: "نتیجه‌ای یافت نشد. املای کلمه را بررسی کنید یا عبارت دیگری را امتحان کنید!",
  autoplayNextSurah: "پخش خودکار سوره بعدی",
  repeatMode: "حالت تکرار",
  repeatNone: "خاموش",
  repeatAyah: "آیه",
  repeatSurah: "سوره",
  repeatAll: "همه",
  detailsAndInfo: "جزئیات و اطلاعات",
  previousAyah: "آیه قبلی",
  playPause: "پخش / توقف",
  nextAyah: "آیه بعدی",
  stop: "توقف",
  mute: "بی‌صدا",
  unmute: "با صادر کردن صدا",
  volume: "حجم صدا",
  playbackSpeed: "سرعت پخش",
  repeat: "تکرار",
  shuffle: "تصادفی",
  autoNext: "بعدی خودکار",

  // Confirms & Headers
  deleteBookmarkConfirm: "آیا مطمئن هستید که می‌خواهید تمام نشانک‌ها را حذف کنید؟",
  deleteNoteConfirm: "آیا مطمئن هستید که می‌خواهید این یادداشت را حذف کنید؟",
  page: "صفحه",
  previousSurah: "سوره قبلی",
  nextSurah: "سوره بعدی",
  inTheNameOfAllah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",

  // Context Menu, Notes & Error Reports
  editNote: "ویرایش یادداشت",
  addNote: "افزودن یادداشت",
  foundAnError: "یافتن خطا",
  reportAnError: "گزارش خطا",
  reportSubmitted: "گزارش ارسال شد!",
  reportThankYou: "با تشکر از گزارش شما. ما در اسرع وقت مشکل را بررسی و برطرف خواهیم کرد.",
  close: "بستن",
  targetContext: "زمینه مورد نظر:",
  errorCategory: "دسته‌بندی خطا:",
  textFont: "متن / قلم",
  audioRecitation: "تلاوت صوتی",
  otherIssue: "سایر موارد",
  description: "توضیحات:",
  describeErrorDetails: "لطفاً جزئیات خطا را در اینجا بنویسید...",
  nameOrEmailOptional: "نام یا ایمیل (اختیاری):",
  yourEmailOrContact: "ایمیل یا اطلاعات تماس شما...",
  cancel: "انصراف",
  submitReport: "ارسال گزارش",
  ayahNotes: "یادداشت‌های آیه",
  writeCustomNotes: "یادداشت‌ها، نکات یا تفاسیر اختصاصی خود را بنویسید",
  typeNoteHere: "یادداشت خود را در اینجا بنویسید...",
  deleteNote: "حذف یادداشت",
  saveNote: "ذخیره یادداشت",
  playWordAudio: "پخش صدای کلمه",
  playRecitation: "پخش تلاوت آیه",
  playFullAyah: "پخش کامل آیه",
  removeLastReadMark: "حذف علامت آخرین مطالعه",
  markAsLastRead: "علامت‌گذاری به عنوان آخرین مطالعه",
  removeBookmark: "حذف نشانک",
  bookmarkAyah: "نشانک‌گذاری آیه",
  shareOnWhatsApp: "اشتراک‌گذاری در واتس‌اپ",
  shareOnTelegram: "اشتراک‌گذاری در تلگرام",
  shareOnX: "اشتراک‌گذاری در X (تویتر)",
  shareOnFacebook: "اشتراک‌گذاری در فیس‌بوک",
  copyAyah: "کپی آیه",
  copied: "کپی شد!",
  word: "کلمه:",
  surahProgress: "پیشرفت سوره"
};
