export const dashboard = {
  quranKareem: "Al-Quran Al-Kareem",
  welcomeSub: "Welcome, Your Portal for Divine Wisdom",
  browseManzil: "Browse Manzil",
  browseHizb: "Browse Hizb",
  browseJuz: "Browse Juz",
  browseSurahs: "Browse Surahs",
  verseOfTheDay: "Verse of the Day",
  lastRead: "Last Read",
  resumeReading: "Resume Reading",
  recitedFrequently: "Recited Frequently",
  tasbihCounter: "Tasbih Counter",
  changeDhikr: "Change Dhikr",
  tapToIncrease: "Tap on the circle to increase count",
};
