export const settings = {
  themeToggle: "Toggle Theme",
  settings: "Settings (Font & Translation)",
  selectTranslator: "Select Translator",
  arabicSize: "Arabic Font Size",
  translationSize: "Translation Font Size",
  saveAndClose: "Save & Close",
  resetPref: "Reset Style",
  help: "Recitation & Guide",
  about: "About App",
  bookmarks: "Bookmarks",
  noBookmarks: "No verses bookmarked yet. Toggle the bookmark ribbon on the verse detail card.",
  helpText1: "1. Play Audio: Click the 'Recite' button below any verse to hear the beautiful recitation by Mishary Alafasy. It auto-advances through verses.",
  helpText2: "2. Save Favorites: Click the bookmark ribbon icon on the left of any verse to store it instantly on your device.",
  helpText3: "3. Customize Style: Use the Settings panel to change Arabic and translation font sizes or switch translators to your preferred choice.",
  aboutText: "A feature-rich, beautiful, and fast Al-Quran portal optimized for all modern desktop and mobile reading layouts.",
  arabicSample: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
  translationSample: "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
  fontResize: "Font Resize",
  readingSettings: "Reading Settings",
  languageName: "English",
  languageSettings: "Language Settings",
  selectLanguage: "Select Language",
  translators: {
    "ur.maududi": "Abul Ala Maududi",
    "ur.jalandhry": "Fateh Muhammad Jalandhri",
    "ur.junagarhi": "Muhammad Junagarhi",
    "en.sahih": "Sahih International",
    "en.yusufali": "Yusuf Ali",
    "en.pickthall": "Pickthall",
    "ar.muyassar": "Al-Muyassar (Tafseer)",
    "ar.jalalayn": "Tafseer Jalalayn"
  }
};
