export const apiManager = {
  // Brand & Navigation
  brandTitle: "Genel API",
  brandSubtitle: "Yüksek Performanslı Açık Kaynak Kur'an REST API",
  badgePublicApi: "Genel API v1.0",
  freeForeverBadge: "%100 Ücretsiz ve Açık Kaynak",
  showSidebar: "Kenar Çubuğunu Göster",
  openMenu: "API Menüsü",
  
  // Navigation Tabs
  overviewTab: "API Genel Bakış",
  explorerTab: "Etkileşimli Gezgin",
  codeGenTab: "Kod Üretici",
  schemaTab: "Veritabanı Şeması",
  metricsTab: "Sistem Metrikleri",
  keysTab: "API Anahtarı Alanı",
  
  // Overview Section
  welcomeTitle: "Küresel Kur'an Uygulamalarını Güçlendiriyoruz",
  welcomeDesc: "Kur'an Alim Açık API Yöneticisine hoş geldiniz. Yüksek performanslı bulut veritabanlarında depolanan kelime kelime Kur'an metinlerine, Osmani/Hint-Pak hatlarına, meallere, transkripsiyonlara, sayfa/cüz düzen koordinatlarına ve ses dosyalarına erişin.",
  quickStartTitle: "Hızlı Başlangıç Kılavuzu",
  quickStartDesc: "Standart HTTP fetch isteklerini kullanarak saniyeler içinde ilk API çağrınızı yapın. Ödeme veya kredi kartı gerekmez.",
  baseUrlTitle: "Canlı Temel URL",
  baseUrlDesc: "Tüm API istekleri aşağıdaki uç nokta URL'sine yönlendirilmelidir:",
  authenticationTitle: "Kimlik Doğrulama Politikası",
  authenticationDesc: "Genel salt-okunur uç noktalar kimlik doğrulama gerektirmez. Daha yüksek istek limitleri için isteğe bağlı olarak 'X-API-Key' başlığında API anahtarı gönderilebilir.",
  rateLimitTitle: "İstek Limiti ve Bant Genişliği",
  rateLimitDesc: "Varsayılan sınır, küresel CDN uç önbelleği ile IP adresi başına dakikada 1000 istektir.",
  corsTitle: "CORS ve Edge Önbellekleme",
  corsDesc: "Access-Control-Allow-Origin tüm uç noktalarda '*' olarak ayarlanmıştır. Ultra hızlı erişim için yanıtlar dünya genelindeki Edge CDN noktalarında önbelleğe alınır.",
  
  // New API Documentation Section
  docSectionTitle: "API Özellikleri ve Dokümantasyon",
  docSectionSubtitle: "Tüm genel uç noktalar için temel URL formatı, istek sınırları ve standart yanıt yapıları hakkında kapsamlı yönergeler.",
  docBaseUrlTitle: "Temel URL Yapısı",
  docBaseUrlDesc: "Tüm genel API uç noktaları, `/api/v1` sürüm ad alanı altında HTTPS üzerinden yönlendirilir. Sürümleme, istemci uygulamaları için geriye dönük uyumluluğu garanti eder.",
  docRateLimitTitle: "İstek Sınırı Yönergeleri",
  docRateLimitDesc: "Kimlik doğrulanmamış genel istekler, IP başına dakikada 1.000 isteğe kadar izin verilir. Önbellekleme sayesinde yinelenen sorgular istek kotasını tüketmez. Özel anahtarlar kapasiteyi 10.000 istek/dakikaya çıkarır.",
  docResponseFormatTitle: "Standart Başarılı Yanıt Formatı",
  docResponseFormatDesc: "Tüm başarılı istekler, yanıt meta verilerini, toplam kayıt sayılarını, yürütme süresini ve istenen veri dizisini içeren tek tip bir JSON zarfı ile HTTP 200 OK durum kodu döndürür.",
  docErrorFormatTitle: "Standart Hata Yanıt Formatı",
  docErrorFormatDesc: "Bir istek geçersiz parametrelerle veya eksik kaynaklarla karşılaştığında, API standart HTTP 4xx/5xx durum kodları eşliğinde yapılandırılmış bir JSON döndürür.",
  
  // Edge API Cache
  cdnCacheTitle: "Edge API Önbellekleme",
  cdnCacheDesc: "Yüksek Performanslı Önbellek API'si (`caches.default`) tarafından desteklenen Edge yanıt önbelleği. Sık yapılan sorgular veritabanına ulaşmadan dünya çapında 300'den fazla Edge noktasından 15 ms'den kısa sürede sunulur.",
  cdnCacheBadge: "Edge Önbelleği Aktif",
  cdnCacheTTL: "Edge TTL: 24 Saat (`s-maxage=86400`)",

  // Endpoints Info
  availableEndpoints: "Temel REST API Uç Noktaları",
  endpointWordsTitle: "Kelime Kelime Kur'an Verisi",
  endpointWordsDesc: "Sure, ayet, kelime konumu, sayfa veya cüz numaralarına göre filtrelenmiş kelime kayıtlarını getirin.",
  endpointSurahTitle: "Sure Birleştirme ve Bilgi",
  endpointSurahDesc: "Herhangi bir Sure (1 - 114) için eksiksiz kelime koleksiyonlarını ve meta verileri alın.",
  endpointSearchTitle: "Tam Metin Kur'an Arama",
  endpointSearchDesc: "Arapça metin (Osmani, Hint-Pak, İmlai), Türkçe/İngilizce mealler veya okunuşlar arasında arama yapın.",
  endpointStatsTitle: "Veri Kümesi İstatistikleri",
  endpointStatsDesc: "Toplam kelime sayılarına, ayet toplamlarına, sayfa dağılımlarına ve veritabanı metriklerine erişin.",
  endpointAudioTitle: "Kelime Ses Dosyaları",
  endpointAudioDesc: "Bulut nesne depolamasından kelime kelime MP3 ses dosyaları için doğrudan akış bağlantıları ve meta veriler.",
  endpointHealthTitle: "API Sağlık Durumu",
  endpointHealthDesc: "Veritabanı bağlantısını ve uç nokta durumunu gösteren gerçek zamanlı sağlık kontrolü uç noktası.",

  // Explorer & Tester
  testerTitle: "Etkileşimli API Deneme Alanı",
  testerDesc: "Uç noktaları doğrudan tarayıcınızdan test edin. Parametreleri ayarlayın, canlı istekler gönderin, durum kodlarını, başlıkları ve JSON yanıtlarını inceleyin.",
  selectEndpoint: "Uç Nokta Seç",
  queryParams: "Sorgu Parametreleri",
  addParam: "Parametre Ekle",
  sendRequest: "İstek Gönder",
  cancellingRequest: "İstek İptal Ediliyor...",
  requestSuccess: "İstek Başarılı",
  requestFailed: "İstek Başarısız",
  responseStatus: "Durum Kodu",
  responseTime: "Yanıt Süresi",
  responseSize: "Yanıt Boyutu",
  responseHeaders: "Yanıt Başlıkları",
  responseBody: "Yanıt Gövdesi (JSON)",
  copyResponse: "Yanıtı Kopyala",
  copiedToast: "Panoya kopyalandı!",
  clearHistory: "Geçmişi Temizle",
  requestHistory: "Son Test Geçmişi",
  paramSurah: "Sure Numarası (1-114)",
  paramVerse: "Ayet Numarası",
  paramSearchQuery: "Arama Metni",
  paramPage: "Mushaf Sayfası (1-604)",
  paramJuz: "Cüz Numarası (1-30)",
  paramLimit: "Sonuç Limiti (Varsayılan 50)",
  
  // Code Generator
  codeGenTitle: "Çok Dilli Kod Parçacıkları",
  codeGenDesc: "Tercih ettiğiniz programlama dili veya çerçevenizde test edilmiş istek kodunu anında kopyalayın.",
  selectLanguage: "Dil / Araç Seçin",
  copyCode: "Kod Parçacığını Kopyala",
  codeCopiedToast: "Kod parçacığı kopyalandı!",

  // Schema Viewer
  schemaTitle: "Kur'an Kelimeleri Veritabanı Şeması (`quran_words`)",
  schemaDesc: "`quranalim` veritabanında yer alan 88.246 Kur'an kelimesi kaydının ayrıntılı dökümü.",
  tableName: "Tablo Adı",
  totalColumns: "Toplam Sütun",
  totalRecords: "Toplam Kayıt",
  columnName: "Sütun Adı",
  dataType: "Veri Türü",
  descriptionHeader: "Açıklama",
  sampleValue: "Örnek Değer",
  r2BucketTitle: "Ses Depolama Alanı (`bucket`)",
  r2BucketDesc: "`quran_words.audio_url` ile senkronize edilmiş kelime kelime MP3 ses dosyalarını barındırır.",

  // Metrics
  metricsTitle: "API Sağlık ve Ağ Metrikleri",
  metricsDesc: "Edge Fonksiyonları, Bulut Veritabanı ve Ses Depolama için canlı operasyonel metrikler.",
  serverStatus: "Sunucu Durumu",
  operational: "Tüm Sistemler Çalışıyor",
  avgLatency: "Ortalama Edge Gecikmesi",
  totalRequestsToday: "Bugünkü Toplam İstek",
  uptimePercent: "Çalışma Süresi (30 Gün)",
  d1Status: "İlişkisel Veritabanı",
  r2Status: "Ses Depolama Alanı",

  // API Key Playground
  keysTitle: "Geliştirici API Anahtarı Üretici",
  keysDesc: "İstek başlıklarını, özel limitleri ve istemci uygulamalarını test etmek için geçici geliştirici anahtarları üretin.",
  generateKey: "Test Anahtarı Üret",
  yourApiKey: "Aktif Test Anahtarınız",
  sandboxKeyNotice: "Test anahtarları başlık testi (`X-API-Key: quran_...`) ve geliştirici entegrasyon testleri içindir.",
  rateLimitTier: "İstek Limiti Seviyesi",
  requestsPerMin: "10.000 istek / dakika",

  // Common UI
  backHome: "Ana Sayfaya Dön",
  toggleSidebar: "Menüyü Aç/Kapat",
  closeMenu: "Menüyü Kapat",
  searchPlaceholder: "Uç noktaları veya parametreleri filtrele...",
  noDataFound: "Belirtilen kriterlere uygun veri bulunamadı.",
  loadingData: "API yanıtı yükleniyor...",
  cancel: "İptal",
  reset: "Sıfırla",
  refresh: "Verileri Yenile",
  copy: "Kopyala"
};
