export const apps = {
  loading: {
    msg: "Tercümeler yükleniyor, lütfen bekleyin...",
    failed: "Dil Paketi Yüklenemedi",
    retry: "Yeniden Dene",
    pack: "Dil Paketi"
  },
  pwa: {
    title: "Kur'an Alim Uygulamasını Yükleyin",
    desc: "Hızlı, çevrimdışı uyumlu erişim ve tam ekran deneyimi için Kur'an Alim uygulamasını ana ekranınıza ekleyin.",
    installBtn: "Uygulamayı Yükle",
    iosGuideTitle: "iOS Uygulama Kurulumu",
    iosGuideDesc: "Kur'an Alim'i iOS cihazınıza yüklemek için: Safari'de Paylaş düğmesine dokunun, aşağı kaydırın ve 'Ana Ekrana Ekle'yi seçin.",
    close: "Kapat",
    howToInstall: "Uygulama Nasıl Yüklenir",
    manualStepsDesc: "Kur'an Alim'i telefonunuza veya bilgisayarınıza yüklemek için:",
    step1: "Tarayıcınızın menüsünü açın (genellikle sağ üstteki üç nokta).",
    step2: "'Uygulamayı Yükle' veya 'Ana Ekrana Ekle' seçeneğini seçin.",
    step3: "Veya tarayıcınızın adres çubuğundaki Yükle simgesine tıklayın.",
    iosStep1: "1. Safari tarayıcısında 'Paylaş' simgesine dokunun.",
    iosStep2: "2. Aşağı kaydırın ve 'Ana Ekrana Ekle'yi seçin."
  },
  titles: {
    home: "Ana Sayfa - Kur'an Alim",
    login: "Giriş Yap - Kur'an Alim",
    signup: "Kayıt Ol - Kur'an Alim",
    forgotPassword: "Şifremi Unuttum - Kur'an Alim",
    resetPassword: "Şifreyi Sıfırla - Kur'an Alim",
    dashboard: "Panel - Kur'an Alim",
    hadith: "Hadis ve Sünnet - Kur'an Alim",
    wuduGuide: "Abdest Rehberi - İslam Fıkhı - Kur'an Alim",
    salahGuide: "Namaz Rehberi - İslam Fıkhı - Kur'an Alim",
    fatawa: "Şeri Sorular ve Fetvalar - İslam Fıkhı - Kur'an Alim",
    zakat: "Zekat Hesaplayıcı - İslam Fıkhı - Kur'an Alim",
    fiqh: "İslam Fıkhı - Kur'an Alim",
    library: "İslami Kütüphane - Kur'an Alim",
    libraryBook: "{book} - Kütüphane - Kur'an Alim",
    libraryChapter: "{chapter} - {book} - Kütüphane - Kur'an Alim",
    tools: "İslami Araçlar - Kur'an Alim",
    about: "Hakkımızda - Kur'an Alim",
    contact: "İletişim - Kur'an Alim",
    donate: "Destek ve Bağış - Kur'an Alim",
    terms: "Kullanım Şartları - Kur'an Alim",
    privacy: "Gizlilik Politikası - Kur'an Alim",
    tos: "Hizmet Şartları - Kur'an Alim",
    disclaimer: "Sorumluluk Reddi - Kur'an Alim",
    quranDashboard: "Kur'an Paneli - Kur'an Alim",
    allSurahs: "Tüm Kur'an Sureleri - Kur'an Alim",
    allJuz: "Tüm Kur'an Cüzleri - Kur'an Alim",
    allHizb: "Tüm Kur'an Hizbleri - Kur'an Alim",
    allManzil: "Tüm Kur'an Menzilleri - Kur'an Alim",
    surah: "Sure {surah} - Kur'an Alim",
    quranDefault: "Kur'an-ı Kerim - Kur'an Alim"
  }
};
