export const dashboard = {
  quranKareem: "el-Kur'anü'l-Kerim",
  welcomeSub: "Hoş Geldiniz, İlahi Hikmet ve İlim Portalınız",
  browseManzil: "Menzillere Göz At",
  browseHizb: "Hizblere Göz At",
  browseJuz: "Cüzlere Göz At",
  browseSurahs: "Surelere Göz At",
  verseOfTheDay: "Günün Ayeti",
  lastRead: "Son Okunan",
  resumeReading: "Okumaya Devam Et",
  recitedFrequently: "Sık Okunan Sureler",
  tasbihCounter: "Tesbih Sayacı",
  changeDhikr: "Zikri Değiştir",
  tapToIncrease: "Sayıyı artırmak için daireye dokunun",
};
