export const driveApp = {
  driveTitle: "Sürücü",
  subtitle: "Sürücü Bulut ve Medya Depolama",
  accessDeniedTitle: "Yönetici Erişimi Gerekli",
  accessDeniedDesc: "Sürücüye erişim yalnızca Yönetici hesaplarıyla sınırlandırılmıştır. Lütfen bir Yönetici hesabıyla giriş yapın.",
  loginRequiredTitle: "Giriş Yapılması Gerekli",
  loginRequiredDesc: "Bulut Depolama yönetimine erişebilmek için Yönetici yetkileriyle giriş yapmış olmalısınız.",
  signInBtn: "Giriş Sayfasına Git",
  demoAdminBtn: "Yönetici Olarak Giriş Yap (Demo)",
  currentRole: "Mevcut Hesap Rolü",
  userRoleUser: "Standart Kullanıcı",
  userRoleAdmin: "Yönetici",
  logoutBtn: "Çıkış Yap",
  switchAccount: "Hesap Değiştir",
  myDrive: "Sürücüm",
  recentFiles: "Son Yüklemeler",
  starredFiles: "Yıldızlı Dosyalar",
  trash: "Çöp Kutusu",
  storageAnalytics: "Depolama Analitiği",
  bucketSettings: "Sürücü Yapılandırması",
  searchPlaceholder: "Dosyaları, klasörleri, uzantıları arayın...",
  uploadFile: "Dosyalar",
  newFolder: "Yeni Klasör",
  refresh: "Sürücüyü Yenile",
  viewGrid: "Izgara Görünümü",
  viewList: "Liste Görünümü",
  filterAll: "Tüm Öğeler",
  filterImages: "Görseller",
  filterAudio: "Sesler",
  filterDocuments: "Belgeler",
  filterArchives: "Arşivler",
  filterOthers: "Diğerleri",
  name: "Ad",
  size: "Boyut",
  type: "Tür",
  modified: "Değiştirilme",
  actions: "İşlemler",
  preview: "Önizleme",
  download: "İndir",
  shareLink: "Bağlantıyı Paylaş",
  rename: "Yeniden Adlandır",
  delete: "Sil",
  restore: "Geri Yükle",
  permanentDelete: "Kalıcı Olarak Sil",
  star: "Yıldız Ekle",
  unstar: "Yıldızı Kaldır",
  details: "Öğe Detayları",
  totalStorage: "Depolama Kapasitesi",
  usedStorage: "Kullanılan Alan",
  freeStorage: "Kullanılabilir Alan",
  filesCount: "Toplam Nesneler",
  foldersCount: "Dizinler",
  uploadModalTitle: "Kur'an Alim Sürücüsüne Dosya Yükle",
  dropzoneText: "Dosyaları buraya sürükleyip bırakın veya seçmek için tıklayın",
  folderModalTitle: "Yeni Dizin Oluştur",
  folderNamePlaceholder: "Klasör adı (ör. Sesler, Kitaplar, Yedekler)...",
  createBtn: "Dizin Oluştur",
  cancelBtn: "İptal",
  noFilesFound: "Bu dizinde dosya bulunamadı.",
  emptyTrash: "Çöp kutusu şu anda boş.",
  publicUrl: "Genel Depolama Bağlantısı",
  copiedToast: "Depolama bağlantısı panoya kopyalandı!",
  deleteConfirm: "Bu öğe Çöp Kutusuna taşınsın mı?",
  permanentDeleteConfirm: "Bu dosya kalıcı olarak silinsin mi? Bu işlem geri alınamaz.",
  adminBadge: "Yönetici Onaylı",
  storageOverview: "Depolama Kapasitesi Genel Bakış",
  fileTypeDistribution: "Dosya Türleri",
  bucketName: "Kur'an Alim",
  statusActive: "Aktif ve Bağlı",
  sidebarLockedTitle: "Depolama Kenar Çubuğu Kilitli",
  sidebarLockedDesc: "Bulut Depolama seçenekleri, meta veriler ve yükleme özellikleri korunmaktadır. Kilidi açmak için lütfen giriş yapın.",
  checkingAuth: "Kimlik Doğrulanıyor...",
  redirecting: "Yönlendiriliyor...",
  loginRedirectNotice: "Sürücüye erişim için giriş yapılması gerekiyor. Giriş sayfasına yönlendiriliyorsunuz...",
  adminRedirectNotice: "Sürücü için yönetici erişimi gerekiyor. Ana sayfaya yönlendiriliyorsunuz...",
  copyUrl: "URL'yi Kopyala",
  close: "Kapat",
  save: "Kaydet",
  itemCount: "Öğeler",
  backToHome: "Ana Sayfaya Dön",
  storageStats: "Depolama İstatistikleri",
  allFolders: "Klasörler ve Dizinler",
  allFiles: "Tüm Dosyalar",
  fileExplorerTitle: "Dosya Gezgini",
  folderTreeTitle: "Dosya Gezgini",
  downloadManager: "İndirme Yöneticisi",
  noFoldersFound: "Henüz oluşturulmuş klasör yok",
  uploadProgress: "Yükleniyor...",
  uploadManager: "Yükleme Yöneticisi",
  addUrls: "URL'ler",
  pasteUrlsLabel: "Dosya URL'lerini yapıştırın veya girin (her satıra bir adet):",
  pasteUrlsPlaceholder: "https://example.com/dosya1.pdf\nhttps://example.com/gorsel2.jpg\nhttps://example.com/arsiv3.zip",
  saveAndUpload: "Kaydet ve Yüklemeyi Başlat",
  cancel: "İptal",
  invalidUrlsNotice: "Lütfen en az bir geçerli URL girin.",
  urlsAddedToQueue: "URL grubu kuyruğa eklendi",
  multipleUploads: "Çoklu Yükleme Yöneticisi",
  quickTools: "Hızlı Araçlar",
  driveSettings: "Sürücü Ayarları",
  defaultLayout: "Varsayılan Düzen",
  autoTrashCleanup: "Çöpü Otomatik Temizle (30 Gün)",
  offlineSync: "Çevrimdışı Dosya Önbelleği",
  storageAlerts: "Düşük Kapasite Uyarıları",
  downloadPreference: "İndirme Kalite Modu",
  uploadNotifications: "Yükleme Bildirimleri",
  settingsSaved: "Ayarlar başarıyla kaydedildi",
  uploadSuccess: "Dosya başarıyla yüklendi!",
  fileSizeError: "Dosya maksimum yükleme boyutu sınırını aşıyor.",
  folderCreatedSuccess: "Klasör başarıyla oluşturuldu!",
  itemDeletedSuccess: "Öğe çöp kutusuna taşındı.",
  itemRestoredSuccess: "Öğe başarıyla geri yüklendi.",
  itemPermanentDeletedSuccess: "Öğe kalıcı olarak silindi.",
  activityLogs: "Aktivite Günlükleri",
  logTitle: "Sürücü Aktivite Günlükleri",
  logSubtitle: "Sistem ve Depolama Denetim İzi",
  logFilterAll: "Tüm Olaylar",
  logFilterFile: "Dosya İşlemleri",
  logFilterSystem: "Sistem ve Güvenlik",
  clearLogs: "Günlük Geçmişini Temizle",
  noLogsFound: "Henüz kayıtlı aktivite günlüğü yok.",
  logActionUpload: "Dosya Yüklendi",
  logActionFolder: "Klasör Oluşturuldu",
  logActionDelete: "Çöp Kutusuna Taşındı",
  logActionRestore: "Öğe Geri Yüklendi",
  logActionStar: "Yıldızlı Dosya",
  logActionSystem: "Güvenlik Denetimi",
  logActionAuth: "Yönetici Oturumu",
  logsClearedToast: "Aktivite günlükleri başarıyla temizlendi",
  previousPage: "Önceki",
  nextPage: "Sonraki",
  pageIndicator: "Sayfa {current} / {total}",
  itemsPerPage: "Sayfa başına öğe",
  showingRange: "{total} öğeden {start} - {end} arası gösteriliyor",
  firstPage: "İlk Sayfa",
  lastPage: "Son Sayfa",
  fileInfo: "Dosya Bilgisi",
  noFileSelected: "Hiçbir Dosya Seçilmedi",
  noFileSelectedDesc: "Özelliklerini ve meta verilerini incelemek için depolama görünümündeki herhangi bir dosya veya klasöre tıklayın.",
  path: "Dizin Konumu",
  dropToUploadTitle: "Yüklemek İçin Dosya veya Klasörleri Sürükleyip Bırakın",
  dropToUploadDesc: "Dosyalar ve klasörler otomatik olarak buraya yüklenecektir:",
  dropzoneActive: "Bırakmak ve yüklemek için fareyi serbest bırakın",
  selectFiles: "Dosyalar",
  selectFolder: "Klasör Seç",
  uploadFolder: "Klasör",
  dropFilesOrFolder: "Dosya veya klasörleri buraya sürükleyip bırakın ya da aşağıdaki seçeneklerden birini seçin",
  uploadQueueProgress: "Yükleme Kuyruğu ve Gerçek Zamanlı İlerleme",
  clearCompleted: "Tamamlananları Temizle",
  startBatchUpload: "Yükleme Kuyruğunu Başlat",
  uploadingQueue: "Kuyruk Yükleniyor...",
  duplicateDetected: "Yinelenen Öğe Algılandı",
  alreadyExistsInFolder: "Dosya veya klasör hedef dizinde zaten mevcut",
  skippedDuplicates: "Yinelenen dosya(lar) veya klasör(ler) atlandı",
  move: "Taşı",
  moveToFolder: "Klasöre Taşı",
  confirmMove: "Taşımayı Onayla",
  publicAccess: "Genel Erişim",
  makePublic: "Herkese Açık Yap",
  publicAccessEnabled: "Genel Erişim Aktif",
  publicAccessDisabled: "Yalnızca Özel Erişim",
  publicLinkCopied: "Genel bağlantı panoya kopyalandı!",
  liveBulkSync: "Canlı Toplu Senkronizasyon (R2'den D1 Veritabanına)",
  syncingD1: "R2 kayıtları D1 ile senkronize ediliyor...",
  lockFolder: "Klasörü Kilitle",
  unlockFolder: "Klasörün Kilidini Aç",
  folderLockedNotice: "Bu klasör kilitli ve korumalıdır. İçeriğe erişmek için kilidini açın.",
  folderLockedToast: "Klasör başarıyla kilitlendi!",
  folderUnlockedToast: "Klasör kilidi başarıyla açıldı!",
  locked: "Kilitli",
};
