export const quranReadHome = {
  backHome: "Ana Sayfaya Dön",
  quranReadingHub: "Kur'an Okuma Merkezi",
  brandSubtitle: "Dijital Kur'an-ı Kerim Merkezi ve Tilavet Rehberi",
  digitalQuranReading: "Dijital Kur'an Okuma ve Takip Sistemi",
  toggleSidebar: "Kenar Çubuğunu Aç/Kapat",
  selectLanguage: "Dil Seçiniz",
  resetProgress: "İlerlemeyi Sıfırla",
  readingStats: "Okuma İstatistikleriniz",
  days: "Gün",
  completedSurahs: "Tamamlanan Sureler",
  surahsFinished: "Tamamlanan Sure %",
  totalVersesRead: "Okunan Toplam Ayet",
  totalVersesPercent: "Toplam Ayet %",
  overallProgress: "Genel Kur'an İlerlemesi",
  recentlyRead: "Son Okunanlar",
  fullyCompleted: "Tamamen Bitti",
  readingUpToAyah: "Okunan Ayete Kadar:",
  readyToRead: "Okumaya Hazır",
  resetConfirm: "Tüm okuma ilerlemenizi sıfırlamak istediğinizden emin misiniz?",
  searchPlaceholder: "Sure adı, numarası veya anlamına göre ara...",
  allSurahs: "Tüm Sureler",
  completed: "Tamamlandı",
  inProgress: "Devam Ediyor",
  notStarted: "Başlanmadı",
  verses: "Ayet",
  rukus: "Rüku",
  juz: "Cüz",
  surahIndexTracking: "Sure Dizini ve Takibi",

  // Daily Ayah & Banner
  dailyAyahTitle: "Günün Ayeti (Âyetü'l-Kürsî)",
  dailyAyahArabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
  dailyAyahTranslation: "Allah, O'ndan başka ilah yoktur; O, Hayy'dır, Kayyûm'dur. Kendisine ne bir uyuklama ne de uyku tutar. Göklerde ve yerde ne varsa O'nundur.",
  readSurahContext: "Bakara Suresini Oku",

  // Quick Modes
  quickModesTitle: "Kur'an Okuma Özellikleri ve Hızlı Modlar",
  mushafMode: "Mushaf Okuma Modu",
  mushafModeDesc: "Klasik 15 satırlık dijital Kur'an'ı sayfa sayfa okuyun.",
  audioReciter: "Sesli Tilavet",
  audioReciterDesc: "Ayet vurgulamalı olarak dünyaca ünlü karilerden dinleyin.",
  bookmarksNotes: "Yer İmleri ve Günlük",
  bookmarksNotesDesc: "Kaydettiğiniz ayetlere, kişisel notlarınıza ve tefekkürlerinize erişin.",
  juzIndex: "30 Cüz Dizini",
  juzIndexDesc: "Tek tıkla 30 Cüzden herhangi birine doğrudan geçiş yapın.",
  statsAnalytics: "Okuma Analitiği",
  statsAnalyticsDesc: "Okuma serinizi, günlük ayetlerinizi ve tamamlama oranınızı takip edin.",
  recommendedSurahs: "Tavsiye Edilen Sureler",
  recommendedSurahsDesc: "Yâsîn, Mülk, Kehf ve Rahmân surelerine hızlı bağlantılar.",

  // Juz Quick Grid
  juzGridTitle: "30 Cüz Gezinme Izgarası",
  juzPara: "Cüz",
  startsAtSurah: "Başlangıç Suresi:",

  // Virtues & Merits
  virtuesTitle: "Kur'an Tilavetinin Faziletleri ve Manevi Faydaları",
  virtue1Title: "Her Harfe 10 Sevap",
  virtue1Desc: "Peygamber Efendimiz (s.a.v.) Kur'an-ı Kerim'in her bir harfini okumanın 10 sevap kazandırdığını bildirmiştir.",
  virtue2Title: "Manevi Rehberlik ve Huzur",
  virtue2Desc: "Kur'an-ı Kerim kalplere huzur verir ve günlük hayatınızı hikmetle aydınlatır.",
  virtue3Title: "Kıyamet Günü Şefaat",
  virtue3Desc: "Kur'an, kıyamet gününde kendisini devamlı okuyan kimselere şefaatçi olacaktır.",
  clearInput: "Metni temizle",
  recentSearches: "Son Aramalar:",
  removeSearch: "Aramayı kaldır",
  clearAllHistory: "Tüm geçmişi temizle",
  clearAll: "Hepsini temizle",
  markAsIncomplete: "Tamamlanmadı Olarak İşaretle",
  markAsCompleted: "Tamamlandı Olarak İşaretle",
  meccan: "Mekki",
  medinan: "Medeni",
  noMatchingSurahs: "Eşleşen sure bulunamadı.",
  startReading: "Okumaya Başla",
  surah: "Sure",
  ayah: "Ayet",
  juzNumber: "Cüz Numarası",
  paraJuz: "Cüz",
  sajdahProstration: "Secde Ayeti",
  yesSajdah: "Evet",
  noSajdah: "Bu Surede Secde Ayeti Yok",
  totalWordsEst: "Tahmini Toplam Kelime",
  totalLettersEst: "Tahmini Toplam Harf",
  introduction: "Giriş",
  keyThemes: "Temel Konular",
  mainLessons: "Ana Dersler",
  virtuesBenefits: "Faziletler ve Faydalar",
  periodRevelation: "Nüzul Dönemi ve Tarihi Bağlam",
  coreSubjects: "Temel Konular ve İtikadi Temalar",
  practicalLessons: "Günlük Hayat İçin Pratik Dersler ve Hikmetler",
  virtuesSpiritual: "Tilavetin Faziletleri ve Manevi Sevapları",
  reflectionTip: "İpucu: Kur'an'ın mesajı üzerinde derinlemesine düşünmek manevi bir rehberlik kaynağıdır. Hazır mısınız? Okumaya geri dönün.",
  loadingVerses: "Kur'an ayetleri yükleniyor...",
  pleaseWait: "Lütfen bir dakika bekleyin",
  failedToLoadSurah: "Sure verileri yüklenemedi",
  tryAgain: "Tekrar Dene",
  loadingNextPage: "Sonraki sayfa yükleniyor...",
  backToTop: "Başa Dön",
  showSurahSidebar: "Sure Kenar Çubuğunu Göster",
  searchVersesInSurah: "Sure İçinde Ayet Ara",
  audioError: "Tilavet sesi yüklenemedi.",
  serverError: "Sunucuya bağlanırken hata oluştu.",

  // Options & Tooltips
  quickOptionsMenu: "Hızlı Seçenekler Menüsü",
  closeMenu: "Menüyü Kapat",
  closeRecitation: "Tilaveti Kapat",
  playSurah: "Sureyi Dinle",
  searchInSurah: "Sure İçinde Ara",
  changeArabicFont: "Arapça Yazı Tipini Değiştir",
  toggleBoldFor: "Kalın Yazıyı Aç/Kapat:",
  changeTextSize: "Metin Boyutunu Değiştir",
  textSize: "Metin Boyutu",
  changeLineHeight: "Satır Aralığını Değiştir",
  lineHeight: "Satır Aralığı",
  changeTextAlignment: "Metin Hizalamasını Değiştir",
  leftAlign: "Sola Hizala",
  centerAlign: "Ortala",
  rightAlign: "Sağa Hizala",
  justifyAlign: "İki Yana Yasla",
  tooltipSettings: "İpucu Ayarları",
  tooltipOptions: "İpucu Seçenekleri",
  translation: "Meal",
  chineseTranslation: "Çince Tercüme",
  chineseSimplified: "Basitleştirilmiş (简体中文)",
  chineseTraditional: "Geleneksel (繁體中文)",
  chinesePinyin: "Pinyin (拼音)",
  chineseZhuyin: "Zhuyin (注音)",
  transliteration: "Okunuş (Transkripsiyon)",
  transliterationStyle: "Okunuş Stili",
  transliterationNormal: "Normal",
  transliterationSyllables: "Heceli",
  transliterationSimpleTajweed: "Basit Tecvid",
  transliterationAdvancedTajweed: "Gelişmiş Tecvid",
  fontSize: "Yazı Boyutu",

  // Sidebar & Navigation
  surahList: "Sure Listesi",
  juzList: "Cüz Listesi",
  hizbList: "Hizb Listesi",
  manzilList: "Menzil Listesi",
  sajdahList: "Secde Listesi",
  rukuList: "Rüku Listesi",
  pageList: "Sayfa Listesi",
  mushafOrder: "Mushaf Sırası",
  revelationOrder: "Nüzul Sırası",
  revelationNo: "Nüzul No",
  surahNo: "Sure",
  hizb: "Hizb",
  manzil: "Menzil",
  sajdah: "Secde",
  surahs: "Sureler",
  bookmarks: "Yer İmleri",
  notes: "Notlar",
  options: "Seçenekler",
  shortcuts: "Kısayollar",
  keyboardShortcuts: "Klavye Kısayolları",
  searchShortcutsPlaceholder: "Kısayolları ara...",
  shortcutHelpTitle: "Faydalı Klavye Kısayolları",
  shortcutHelpDesc: "Kur'an okuyucu için hızlı gezinme ve kontrol tuşları.",
  categoryAudio: "Ses ve Tilavet",
  categoryNavigation: "Gezinme ve Okuma",
  categoryInterface: "Arayüz ve Arama",
  shortcutPlayPause: "Sesi Oynat / Duraklat",
  shortcutNextVerse: "Sonraki Ayet",
  shortcutPrevVerse: "Önceki Ayet",
  shortcutSearch: "Arama Çubuğunu Aç",
  shortcutToggleSidebar: "Kenar Çubuğunu Aç/Kapat",
  shortcutBookmark: "Ayeti Yer İmlerine Ekle",
  shortcutNextSurah: "Sonraki Sure",
  shortcutPrevSurah: "Önceki Sure",
  shortcutCloseModal: "Pencereleri Kapat",
  shortcutScrollTop: "Sayfanın Başına Git",
  keySpace: "Boşluk Tuşu",
  keyArrowRight: "→ Sağ Ok",
  keyArrowLeft: "← Sol Ok",
  keyArrowUp: "↑ Yukarı Ok",
  keyArrowDown: "↓ Aşağı Ok",
  keyEsc: "Esc",
  keyCtrlK: "Ctrl + K",
  keyCtrlB: "Ctrl + B",
  keyShiftN: "Shift + N",
  keyShiftP: "Shift + P",
  noShortcutsFound: "Eşleşen kısayol bulunamadı.",
  recitationAndSearch: "Tilavet ve Arama",
  textAppearance: "Metin Görünümü",
  searchSurah: "Sure Ara...",
  searchJuz: "Cüz Ara...",
  searchHizb: "Hizb Ara...",
  searchManzil: "Menzil Ara...",
  searchSajdah: "Secde Ara...",
  recent: "Son:",
  clear: "Temizle",
  noSurahsFound: "Sure Bulunamadı",
  noJuzFound: "Cüz Bulunamadı",
  noHizbFound: "Hizb Bulunamadı",
  noManzilFound: "Menzil Bulunamadı",
  noSajdahFound: "Secde Ayeti Bulunamadı",
  typeMeccanLabel: "Mekki",
  typeMedinanLabel: "Medeni",
  versesLabel: "Ayet",
  noBookmarks: "Henüz kayıtlı yer imi yok.",
  ayahNo: "Ayet ",
  hideSidebar: "Kenar Çubuğunu Gizle",
  showSidebar: "Kenar Çubuğunu Göster",
  closeSidebar: "Kenar Çubuğunu Kapat",
  loadAllPages: "Tüm Sayfaları Yükle",

  // Search & Playback Controls
  searchVersesPlaceholder: "Bu surede herhangi bir kelime arayın...",
  resultsFound: "{count} sonuç bulundu",
  noResultsFound: "Sonuç bulunamadı. Yazımı kontrol edin veya başka bir arama terimi deneyin!",
  autoplayNextSurah: "Sonraki Sureyi Otomatik Çal",
  repeatMode: "Tekrar Modu",
  repeatNone: "Kapalı",
  repeatAyah: "Ayet",
  repeatSurah: "Sure",
  repeatAll: "Tümü",
  detailsAndInfo: "Detaylar ve Bilgi",
  surahInfo: "Sure Bilgisi",
  previousAyah: "Önceki Ayet",
  playPause: "Oynat / Duraklat",
  nextAyah: "Sonraki Ayet",
  stop: "Durdur",
  mute: "Sesi Kapat",
  unmute: "Sesi Aç",
  volume: "Ses Seviyesi",
  playbackSpeed: "Çalma Hızı",
  repeat: "Tekrarla",
  shuffle: "Karıştır",
  autoNext: "Otomatik İlerle",

  // Confirms & Headers
  deleteBookmarkConfirm: "Tüm yer imlerini silmek istediğinizden emin misiniz?",
  deleteNoteConfirm: "Bu notu silmek istediğinizden emin misiniz?",
  page: "Sayfa",
  previousSurah: "Önceki Sure",
  nextSurah: "Sonraki Sure",
  inTheNameOfAllah: "Rahmân ve Rahîm olan Allah'ın adıyla",

  // Context Menu, Notes & Error Reports
  editNote: "Notu Düzenle",
  addNote: "Not Ekle",
  foundAnError: "Hata mı Buldunuz?",
  reportAnError: "Hata Bildir",
  reportSubmitted: "Bildirim Gönderildi!",
  reportThankYou: "Bildiriminiz için teşekkür ederiz. En kısa sürede inceleyip düzelteceğiz.",
  close: "Kapat",
  targetContext: "İlgili Bölüm:",
  errorCategory: "Hata Kategorisi:",
  textFont: "Metin / Yazı Tipi",
  audioRecitation: "Sesli Tilavet",
  otherIssue: "Diğer Sorun",
  description: "Açıklama:",
  describeErrorDetails: "Lütfen hata detaylarını buraya yazın...",
  nameOrEmailOptional: "Ad veya E-posta (İsteğe Bağlı):",
  yourEmailOrContact: "E-posta veya iletişim bilgileriniz...",
  cancel: "İptal",
  submitReport: "Bildirimi Gönder",
  ayahNotes: "Ayet Notları",
  writeCustomNotes: "Kişisel notlarınızı, tefekkürlerinizi veya tefsir bilgilerinizi yazın",
  typeNoteHere: "Notunuzu buraya yazın...",
  deleteNote: "Notu Sil",
  saveNote: "Notu Kaydet",
  playWordAudio: "Kelime Sesini Dinle",
  playRecitation: "Ayet Tilavetini Dinle",
  playFullAyah: "Tüm Ayeti Dinle",
  removeLastReadMark: "Son Okunan İşaretini Kaldır",
  markAsLastRead: "Son Okunan Olarak İşaretle",
  removeBookmark: "Yer İmini Kaldır",
  bookmarkAyah: "Ayeti Yer İmlerine Ekle",
  shareOnWhatsApp: "WhatsApp'ta Paylaş",
  shareOnTelegram: "Telegram'da Paylaş",
  shareOnX: "X'te Paylaş",
  shareOnFacebook: "Facebook'ta Paylaş",
  copyAyah: "Ayeti Kopyala",
  copied: "Kopyalandı!",
  word: "Kelime:",
  surahProgress: "Sure İlerlemesi",
  inQuran: "Kur'an'da",
  inSurah: "Surede",
  times: "kez",
  allWords: "Tümü",
  uniqueWords: "Benzersiz",
  groups: "Gruplar",
  previous: "Önceki",
  next: "Sonraki",
  of: "/",
  playAudio: "Sesi Oynat",
  backToSurah: "Okumaya Dön",

  // Reciter & Qaris
  reciter: "Kari / Okuyucu",
  selectReciter: "Kari Seç",
  searchReciters: "Kari adına veya kıraat tarzına göre ara...",
  qiratStyle: "Kıraat Tarzı",
  defaultReciter: "Şeyh Mişari Raşid el-Afasi (Hafs - Murattal)",
  allReciters: "Tüm Kariler (20)",

  // Audio Sync Section
  audioSyncTitle: "Veritabanı Ses Dosyaları Senkronizasyonu (quran_audio_files)",
  audioSyncSubtitle: "Eksiksiz ses dosyalarını ve kelime zamanlama segmentlerini D1 Veritabanı 'quranalim' içine kaydedin (tablo: quran_audio_files)",
  syncAllSurahsBtn: "Tüm 114 Sureyi Veritabanına Senkronize Et",
  syncingDbProgress: "Ses Dosyaları Veritabanına Senkronize Ediliyor...",
  syncCompletedSuccess: "'quranalim' veritabanındaki 'quran_audio_files' tablosuna ses dosyaları başarıyla senkronize edildi!",
  dbTableStatus: "D1 Tablo Durumu: quran_audio_files",
  syncedRecords: "Veritabanındaki Senkronize Kayıtlar:",
  dbBindingName: "D1 Veritabanı Bağlantısı: DB (quranalim)"
};
