export const settings = {
  themeToggle: "Temayı Değiştir",
  settings: "Ayarlar (Yazı Tipi ve Meal)",
  selectTranslator: "Mütercim / Meal Seç",
  arabicSize: "Arapça Yazı Boyutu",
  translationSize: "Meal Yazı Boyutu",
  saveAndClose: "Kaydet ve Kapat",
  resetPref: "Stili Sıfırla",
  help: "Tilavet ve Rehber",
  about: "Uygulama Hakkında",
  bookmarks: "Yer İmleri",
  noBookmarks: "Henüz hiçbir ayet yer imlerine eklenmedi. Ayet kartındaki kurdele simgesine tıklayarak ekleyebilirsiniz.",
  helpText1: "1. Sesli Dinleme: Mişari Raşid el-Afasi'nin tilavetini dinlemek için herhangi bir ayetin altındaki 'Dinle' düğmesine tıklayın. Ayetler otomatik olarak sırayla devam eder.",
  helpText2: "2. Favorilere Ekleme: Herhangi bir ayeti cihazınıza anında kaydetmek için ayetin solundaki yer imi simgesine tıklayın.",
  helpText3: "3. Stili Kişiselleştirme: Arapça ve meal yazı boyutlarını değiştirmek veya tercih ettiğiniz mütercimi seçmek için Ayarlar panelini kullanın.",
  aboutText: "Modern masaüstü ve mobil okuma düzenleri için optimize edilmiş, zengin özellikli, şık ve hızlı Kur'an-ı Kerim portalı.",
  arabicSample: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
  translationSample: "Rahmân ve Rahîm olan Allah'ın adıyla.",
  fontResize: "Yazı Boyutunu Ayarla",
  readingSettings: "Okuma Ayarları",
  languageName: "Türkçe",
  languageSettings: "Dil Ayarları",
  selectLanguage: "Dil Seçiniz",
  translators: {
    "ur.maududi": "Ebu'l-A'lâ el-Mevdûdî",
    "ur.jalandhry": "Fetih Muhammed Câlendherî",
    "ur.junagarhi": "Muhammed Cûnegadî",
    "en.sahih": "Sahih International",
    "en.yusufali": "Yusuf Ali",
    "en.pickthall": "Pickthall",
    "ar.muyassar": "el-Muyesser (Tefsir)",
    "ar.jalalayn": "Celâleyn Tefsiri"
  }
};
